By early Friday, Cyclone Sidr weakened into a tropical storm after hitting the capital city of Dhaka.
United News of Bangladesh reports that 1100 have been killed thus far, and country officials anticipate thousands of corpses will be found in the worst hit districts.
Sidr had a tidal surge of seven feet high.
Meanwhile reliefs efforts continue to pour in.
The European Commission sent 1.5 million euros; Germany 500,000 euros; International Red Cross and Red Crescent 152,000 euros; and a Swiss Church Charity 121,000 euros.
Most pressing needs are: food, safe-drinking water, clothing, blankets, medicine, and of course, emergency shelters.
