Flight KI-574 is still missing.
Reports of recovered casualties and wreckage given by local people were not substantiated.
Indonesian officials apologized for reporting false information.
Halfway through the ill-fated plane’s two-hour flight, it changed course twice, first for weather and then for high winds.
There were no distress calls.
At 15:07 Jakarta time on Monday, the plane vanished.
No transmissions from its emergency locator have been detected.
A massive search and rescue mission continues involving nearly 3,000 soldiers, police and civilians, Singaporean crews and a U.S. NTSB team.
Three Americans were on the plane.
Officials will continue the search indefinitely.
