Food safety has become a major concern of Chinese people.
According to a 2006 survey 65 percent of the respondents worried about food safety in China.
Tainted food impacts at least 300 million people annually.
Food poisoning killed 196 people in China last year.
During one week in 2006 China had four mass food poisoning incidents.
China has 9 ministries that independently implement food safety rules that are at times overlapping, confusing, and contradictory.
A Chinese lawmaker has appealed to set up a trans-ministry agency to carry out the responsibilities which are undertaken by several government departments, for food safety.
