Overfishing and poaching have caused worldwide tuna stocks to plummet toward extinction.
Tuna is an important food source, particularly for Japan, which consumes 25% of the world’s catch.
In Kobe, Japan, representatives from five international tuna conservation organizations and over 60 countries and regions met to negotiate a plan to reverse the decline.
The plan, expected to be adopted Friday, includes improved communication between the regulatory bodies, establishment of an international inspection team, and electronic monitoring and tagging to stop poaching.
In October and November, commissions agreed to sharply reduce the global catch of southern bluefin and Mediterranean-caught bluefin tuna.
