On 3 February 2008 at 10:00 a.m. two Palestine suicide bombers attempted to carry out a bombing attack at a shopping mall in the Israeli city of Dimona, ten kilometers from the alleged site of Israel’s top-secret nuclear reactor.
The first bomber detonated his explosive belt, killing an Israeli woman and injuring eleven people.
Israeli police foiled a second attack by shooting the other bomber before the device on his body exploded and then detonating his explosive belt.
The total number of people killed was three.
Four different groups claimed responsibility for the attack.
