Increasingly sophisticated software installs itself on computers to create zombie armies (botnets).
Criminals use botnets’ collective power maliciously or to defraud or steal data.
Botnets, present on 11 percent of predominantly Windows-based computers, briefly overwhelmed global traffic management in 2002 and 2007.
Companies Beyond Security and Damballa focus on controlling botnets.
Registry manager VeriSign is boosting capacity tenfold and dispersing operations to 70 sites.
Users need to use firewalls, antivirus and anti-phishing software.
Researchers are exploring redesigning the open, trusting Internet to authenticate everything.
China and Iran censor the Internet against subversion or immorality.
China’s extensive cyber-police arrests virus creators.
