Indonesian officials admitted on January 2 that the wreckage of a passenger jet that had disappeared the previous day had not been found.
They blamed incorrect information from local villagers and police for the confusion.
Subsequent land, sea, and aerial searches over an area the size of California turned up no evidence of the missing jetliner although a woman on Sulawesi Island had reported seeing a low flying aircraft and hearing an explosion.
No signals from the plane’s emergency locator were detected.
Singapore and a team from the U.S. NTSB were participating in the search as of January 6.
