On 11 March 2004 ten bombs exploded on four commuter trains in Madrid, killing 191 people and injuring over 1,800.
Police deactivated a bomb hidden on one of the trains.
On March 13 Police arrested three Moroccans and two Indians, alleged masterminds of the bombings.
A European spokesman for al-Qaida claimed responsibility for the bombings as a revenge for Spanish troop presence in Iraq and Afghanistan.
On April 3, 2004 seven major bombing suspects blew themselves up in Madrid.
The trial date for the 29 suspects accused of involvement in the bomb attacks was set for 15 February 2007.
