In mid-March, Menu Foods, an Ontario-based manufacturer of dog and cat food, recalled 60 million containers of its pet foods following reports of kidney failure and death.
The recall affects retailers throughout the United States, Canada, and Mexico, including the top-brand pet food companies.
Sellers have pulled the products off their shelves, and the recall may cost Menu Foods up to $34 million.
Menu Foods has not determined the cause of the reported deaths, but has agreed to compensate owners who have lost pets.
The FDA is testing for contaminated wheat gluten, a filler used in pet foods.
