Federal and NY state investigators discovered aminopterina rodenticide in the pet food blamed for killing at least 14 animals in the U.S. How the unapproved rat poison got into the pet food is yet unknown.
Ten confirmed cases of diet-related renal failure were diagnosed at a Manhattan veterinary medical center where one cat died.
The recall has led to at least three lawsuits against Menu Foods from owners seeking compensation for the loss of beloved family pets, high veterinary bills and continuing care costs for surviving animals.
The plant found to have produced the tainted pet food has been closed.
