Federal and New York state authorities say that rat poison has been found in pet foods recently recalled by Menu Foods following the deaths of a number of animals.
Officials are unsure of how the poison, aminopterina rodenticide, got into the products, which are sold under 91 separate brand names, and cannot rule out sabotage.
The contaminated food has been blamed for the deaths of at least 14 cats and dogs.
Menu Foods’ recall has prompted the filing of a class action lawsuit in Canada and several individual lawsuits in U.S. courts.
