In February 2007 Spain’s National Court began the trial of 29 suspects in the March 2004 Madrid train bombings.
Suspected bombing organizers are Rabei Ousmane Sayed Ahmed, Hassan Al Haski, and Youssef Belhadj.
Suspected bombers are Jamal Zougam, Abdelmajid Bouchar, and Basel Ghalyoun.
Jose Emilio Suarez Trashorras is suspected of supplying explosives.
All are charged with 191 murders and 1,824 attempts and face 38,656-year sentences (legally only 40 years).
Ousmane is also charged with running a terrorist organization.
He rejected all charges against him and refused to give evidence.
Remaining suspects are charged with terrorist group collaboration and falsifying documents.
