Roberts brought additional weapons and items to the schoolhouse siege, indicating he possibly intended molesting the girls, ages 6-13.
Roberts released 15 boys and 4 adults.
One girl escaped.
A teacher alerted a farmer to call 911 at 10:35 a.m.
State police responded.
During the siege, Roberts expressed anguish over the 1997 death of a newborn daughter in addition to being haunted by unsubstantiated memories.
All of the hospitalized girls were released by Christmastime.
Four are returning to school.
One remains permanently disabled.
The schoolhouse was demolished on Oct. 12.
A new building, under construction nearby, will be completed mid-February.
