Monday morning, October 2, Charles Carl Roberts IV, 32, armed with a handgun and shotgun, laid siege to the one-room West Nickel Mines Amish School in Lancaster County, PA.
After releasing adult and male occupants, Roberts bound 10 girls and shot each execution-style and then himself at around 10:45 a.m.
Police found Roberts and three girls dead at the scene.
Seven wounded were transported to hospitals, where two girls died.
During the siege, Roberts called his wife and claimed that torment for having molested two girls 20 years earlier motivated the attack.
However, his supposed victims recall no such abuse.
