On Thursday, November 15, 2007, Cyclone Sidr moved north from Bengal Bay striking Bangladesh's southern coast and its low-lying offshore islands.
Wind velocity reached 155 MPH and its cloud mass was 310 miles wide.
Disaster-prone Bangladesh lost 500,000 people from a 1970 cyclone, but only 138,000 in a 1991 cyclone.
This lower death toll was attributed to installation of cyclone shelters and warning systems.
As of Friday, an unofficial death toll was 163, with 650,000 being forced to evacuate.
Upon being alerted, the U.S. Mission in Bangladesh prepositioned supplies and equipment.
The U.N World Food Program (WFP) also sent food.
