On 11 April 2006 the investigative judge of the Madrid bombings, indicted 29 people, 15 of them Moroccans.
The Judge concluded on 7 July 2006 that the attack was carried out by a cell of Muslim extremists angry over the Spanish government’s support for the Iraq war.
On 6 November prosecutors sought jail terms exceeding 38,000 years for each of 7 leading suspects.
The trial began in February 2007 and a verdict is expected in October.
The first two defendants, both bombing masterminds, refused to answer questions and denied having anything to do with the attack.
