An Indonesian passenger plane carrying 102 people disappeared in stormy weather on New Years Day 2007.
The Adam Air Boeing 737-400 was 17 years old, but reportedly in good mechanical condition.
One hour after taking off from Java Island enroute to Sulawesi, it began sending distress signals and then disappeared from the radar screen.
Rescue teams, assisted by local residents, reportedly found the wreckage in the mountainous region of West Sulawesi.
At least 90 of the 102 people were killed.
One flight expert attributed the accident to an air pocket, and the plane's failure to fly at 35,000 feet.
