The United States condemned the suicide attack on Israel, the first since January 2007.
It said it would urge any states that have influence with Palestinians on the West Bank or in Gaza to request that they cease their attacks.
Meanwhile, gunmen in the southern Gaza town of Rafah, fired their weapons to celebrate the attack on Israel.
The Islamist Hamas movement claimed responsibility for the bombing on February 5th.
Earlier, three other militant groups including the Martyr's Brigades, the Islamists' main rivals, took credit.
Israel's Security remains concerned because their border with Egypt can only be desribed as porous.
