On Friday, March 16, 2007, Menu Foods of Streetsville, Ontario, began recalling 60 million containers of pet food after reports of ten animal deaths.
Menu's dog foods are sold under 48 brands and cat foods under 40 brands.
This company sells its products in the U.S., Canada and Mexico, and provides its products to 17 of the top 20 North American retailers.
The foods may have become contaminated by wheat gluten purchased from a new supplier which caused kidney failure in the animals.
The recalls bear code dates of 6339 through 7073.
The company will compensate owners of deceased animals.
