On January 1, an Indonesian Boeing 737-400 aircraft, Adam Air flight KI-574, crashed in a mountainous region of West Sulawesi province, killing 90 of the 102 persons on board.
Three Americans were among the passengers.
Search teams arrived at the crash scene on the following day and found 12 survivors, all in critical condition.
The cause of the crash was not immediately known, but transportation officials thought the aircraft might have hit an ''air pocket,'' a phenomenon not unknown in that region.
The aircraft had made a single distress call prior to going down.
