Fisheries management organizations adopted a nonbinding plan to reverse tuna stock declines.
It calls for closer communication, sharing data on illegal fishing and stock assessment, an international high seas inspection team, transparent criteria for quota allocation, and support for small coastal states in combating illegal fishing.
Plastic tags could be replaced by electronic tags for tracking.
Some want tougher reviews for regulators.
Overfishing and poaching are blamed for tuna’s decline.
Fleet size needs to fit quotas rather than capacity and profit determining catch size.
The EU, Japan and Morocco reduced their quotas by over 20 percent, Turkey by 13 percent.
