In 2007 China was the top violator of US food safety standards, with the US rejecting 257 Chinese shipments.
One case involved contaminated pet food suspected of killing thousands of pets.
International food scares involving Chinese exports led to a crackdown on food exports.
Authorities uncovered 23,000 safety violations and closed down 180 food plants.
Chinese authorities blacklisted 14 companies for planning to export substandard food products and banned them from future exports.
In response to concerns about the safety of its food exports China stated it was willing to work with the world community on improving food security.
