Kobe summit representatives agreed in principle to an unprecedented international plan to curb tuna overfishing.
The plan’s measures are nonbinding, and no specific catch quotas were provided.
Conservationists are disappointment that the plan didn’t go farther to control the tuna fishing industry and address the environmental damage it causes.
A follow-up meeting is scheduled for early 2008 in the US.
Recent negotiations in Tokyo resulted in the EU and Japan agreeing to slash their bluefin tuna quotas in the Mediterranean and Atlantic by over 20% by 2010 and a plan to split tuna quotas among 43 countries and regions.
