Prior to shooting the young girls, Charles Roberts, a quiet milkman and father of three, called 911 saying he wanted everyone off the school property.
Allegedly, he was angry at God for the death of his first child, and before shooting, he told the girls: ''I am going to make you pay for my daughter''.
Today, four of the wounded girls are back in school, while the fifth is fully disabled.
The bloodied schoolhouse has been demolished and a new one is being built.
The Amish have forgiven everyone, and a community group has raised $3.6 million for the victims.
