The contaminant in the pet foods responsible for killing 14 animals were found to be rat poison.
Researchers from Cornell University made this discovery on Thursday evening, March 22nd.
The FDA did not theorize on how the toxin got into the food, but did not rule out 'sabotage'.
All of the foods involved were produced at Menu Foods' plant in Emporia, Kansas.
Officials are still unsure if the wheat gluten was the source of the rat poison.
Company staff said they receive some wheat gluten from China.
For more information, customers can call 866-895-2708 or use web site www.menufoods.com.
