On Wednesday, 3 January, Indonesian authorities reported that claims of finding the missing aircraft and 12 survivors were false.
On the following Saturday, a U.S. National Transportation Safety Team arrived to help probe the apparent crash.
Patrick Smith, a U.S. Aviation Commentator speculated that the plane may have crashed at sea into an underwater trench prohibiting signal transmissions.
Nearly 3000 Indonesian searchers have been trudging through the dense jungles, while ships and aircraft have searched an area the size of California, with no findings.
Fifty protestors gathered in Jakarta Friday demanding resignation of the transport minister over the erroneus reports.
