Internet security needs a global approach because it is a global problem.
Pakistan tried to block a riot-sparking video and accidentally blocked world YouTube access.
Internet sabotage shut down digital infrastructure in Estonia and Bangladesh.
Overseas hackers accessed confidential information from South Korea.
China and Taiwan are both accused of Internet attacks to steal secret data.
The U.S. considered including cyberspace regulation in rules of international warfare.
South Korea’s real-name system authenticates identity information on applications for online accounts.
The UAE is establishing a computer emergency response team.
Computer whizzes sell security vulnerability information to both software vendors and criminals.
