On February 5, Hamas claimed responsibility for the previous day’s suicide bombing in Dimona, Israel, which killed one civilian and wounded 10 others.
This was Hamas’s first such claim since 2004.
Immediately following the bombing, the al-Aqsa Martyrs Brigade and two other Palestinian militant groups had also claimed responsibility.
The Israelis continued to suspect that the two suicide bombers had entered the country from Gaza or Egypt, but officials did not think the attack was aimed at Israel’s nuclear facility in Dimona.
Israeli Prime Minister Ehud Olmert declared that Israel would ''not relent'' in its struggle with terrorism.
