Menu Foods voluntarily recalled 60 million containers of wet cat and dog food distributed throughout North America following complaints of pets’ kidney failure and deaths.
Menu recalled 48 brands of dog food and 40 brands of cat food sold between December 1 and March 6.
Of the 10 known food-related deaths, 7 occurred during a taste test Menu conducted February 27, a week after receiving complaints.
Mid-March, Menu alerted the FDA of its findings.
The FDA is focusing its investigation on the filler wheat gluten.
The incidence of pet illness coincided with Menu’s use of a new supplier, since dropped.
