China's State Food and Drug Administration (SFDA) is in its fourth year of evaluating food safety in 31 major cities.
Tainted food impacts at least 300 milion Chinese every year.
Many of the foods impacted are snails, pork, turbots, and eggs.
According to an SFDA survey, 65 percent of the respondents are worried about food safety in China.
Ren Yuling, a top political advisor, said current punishments are too slack in the food safety arena.
Zheng Xinsui, a congressional deputy, said new food safety criteria are needed, and officials held responsible.
Another official said new amendments are coming soon.
