On November 15, 2007, cyclone Sidr with 140-155 mph winds and torrential rain hit the SW Bangladesh coast near the Indian border.
For two days before, Bangladeshi and Indian officials raced to evacuate 650,000 people from the coastal area, trying to avoid the high death tolls of 1970 and 1991 storms.
Hundreds died and tens of thousands were left homeless.
The impact was mitigated by stockpiled food and supplies, shelters, and wave barriers set up by the US, CARE and Save the Children.
The US Mission was ready with emergency equipment.
Germany sent relief funds and the UN sent food.
