On February 4, 2008, a suicide bomber attacked an Israeli shopping mall in Dimona, 10 kilometers from a nuclear reactor site.
A second bomber was killed before he could detonate his explosive belt.
Two weeks earlier, the Egyptian/Gaza border was breached, and Israeli security was concerned that terrorists might infiltrate.
Reports on the number killed and wounded vary from 1-4 and 10-16 respectively.
The military wing of Palestinian President Mahmoud Abbas' Fatah movement claimed responsibility; however the Palestinian National Authority said it condemns every operation that targets civilians.
The al-Aqsa Martyrs Brigades of Fatah also took credit for the attack.
