A February 4 suicide bombing at a shopping mall in the Israeli town of Dimona killed an Israeli woman and wounded 11 other persons.
A second would-be bomber was shot dead by police before he could detonate his explosive vest.
Dimona is the site of Israel’s nuclear reactor.
Fatah’s al-Aqsa Martyrs Brigades claimed credit for the attack, although Fatah initially denied involvement.
A spokesman for the group said that the bombers had entered Israel from the West Bank rather than from Gaza or Egypt.
Israel expects to complete a security fence along the border with Gaza by 2010.
