The United States condemned the suicide bombing in the Israeli town of Dimona and vowed to continue its effort to promote Middle East Peace.
While the attack took place ten kilometers from the Dimona nuclear reactor, Israeli government officials did not believe the reactor was the attackers’ target.
Palestinian militants groups announced that the two suicide bombers were from the Gaza Strip, while Al Aqsa Martyrs’ Brigades had earlier claimed the bombers were from the West bank to divert attention from the Gaza connection.
Following the attack Israeli Prime Minister Ehud Olmert pledged to continue relentlessly to fight terrorism.
