An Indonesian Boeing 737-400 carrying 102 people crashed into a mountain near Polewali in West Sulawesi Monday afternoon.
Adam Air Flight KI-574 departed Surabaya at 12:59 p.m., headed for Manado and flying into stormy weather.
After sending a distress call, it disappeared from radar.
Emergency crews, dispatched Tuesday at dawn, found the wreckage at 8:29 a.m.
At least 90 were killed.
Twelve survivors were transported to a hospital by foot.
Authorities believe the plane was flying at 8,000 rather than 35,000 feet, making it vulnerable to air disturbances.
They suspect the plane hit an air pocket, causing it to crash.
