Cyclone Sidr’s driving rain and 7-foot high tidal surge left thousands homeless.
1,070 people were confirmed dead, with the number expected to reach thousands.
Most died when trees fell on flimsy homes built of bamboo and tin.
The Sundarbans mangrove forest and its 450 Royal Bengal tigers were feared heavily damaged.
Power and telephone lines were down.
The EC and world charities released funds for emergency supplies.
Army and relief workers battled to reach worst-hit districts.
Officials were optimistic the early warning system and network of cyclone shelters introduced after the disastrous 1991 storm would spare the country mass casualties.
