On October 6, 2006, five young girls were killed ''execution style'' at Nickel Mines Amish School, Lancaster County, Pennsylvania.
Charles Carl Roberts IV, a local truck driver, entered the school around 9 a.m.
He forced the adults and boys out, and bound up the girls.
After shooting five in the head, he seriously wounded the others before killing himself.
In notes, Roberts said he was tormented by memories of molesting two young female relatives 20 years earlier.
Both relatives, however, claimed nothing happened.
He brought sexual lubricant to school, but it's unclear whether he molested any of the girls.
