On May 22, 2007, China announced it would work with the world community regarding concerns of its edible exports.
In June 2007, China closed 180 food plants where 23,000 violations had occurred.
One problem for China, it lacks refrigerated trucks (only 30,000); the U.S. has 280,000.
On July 18th, China and the U.S. announced they would sign a food safety agreement by year's end.
By September 1st, all exports to the U.S. will bear the sign "CIQ" meaning 'China Inspection and Quarantine'.
In June, the Chinese head of the Food and Drug Watchdog Agency was executed for accepting bribes.
