Cyber security is a global problem requiring global solutions.
In 2007 Estonia experienced one of the first cyberspace wars, lasting a month.
A survey of Taiwan’s Internet users revealed that the number of Internet users worried about Internet security increased nearly 18 % between 2003 and 2007.
The United Arab Emirates contracted with Symantec to set up a computer emergency response team to improver cyber security.
In November 2007 Bangladesh’s Internet link was sabotaged.
Senator Bill Nelson believes we must protect US cyberspace interests against Chinese threats.
South Korea’s presidential mansion came under attack during 2008 from overseas hackers.
