Computer hackers are using sophisticated weapons to create global internet crimes.
They use programs that install themselves on personal computers and bind the computers together to create ''botnets''.
In February 2007 hackers overwhelmed 3 of 13 computers that help manage global computer traffic for 12 hours.
China leads world efforts to control the Internet with its armies of cyber-police.
VeriSign, a Silicon Valley company, spent $100 million to combat a new wave of computer attacks.
The number of US companies fighting computer security problems has decreased.
Researchers are exploring ways to redesign the Internet, building security features into it.
