By Sunday, 12 miles of Mallipo coastline were affected by the oil spill.
An ever-increasing number of troops, police, volunteers and residents, about 7,500 in all, labored to remove oil from the shore using buckets and shovels.
Oil fumes and a lack of equipment have hindered clean-up operations, which are expected to continue for two months.
Military ships and private fishing vessels continued to work to contain the oil and clean the waters, using booms and skimmers.
For Mallipo beach the oil spill is an environmental disaster.
The area’s 181 aquatic seafood farms, fishing industry and tourism are in jeopardy.
