About 800 pediatric cold products sold in the US contain some 39 drugs considered unsafe for young children.
Potentially unsafe drugs include dextromethorphan, brompheniramine, phenylephrine, chlorpheniramine, and pseudoephedrine.
Adverse effects include heart, breathing and neurological problems, brain scarring, convulsions and seizures.
Children with heart problems are especially at risk.
Stimulants keep children wake, other drugs sedate them.
An expert FDA panel voted to ban over-the-counter cold products for children under age 6.
Because children and adults react differently to medicine, it called for new research to test products in children.
Doctors advise parents to use acetaminophen or alternative non-medical treatments.
