On December 7, 2007, a Hong Kong-registered oil tanker, the Hebei Spirit, spilled about 66,000 barrels of crude oil following a collision with a barge off the western coast of South Korea.
It was thought to be South Korea’s largest maritime oil spill.
Officials, fearing environmental damage to the coast and to fisheries in the area, immediately dispatched dozens of vessels and four helicopters to the site to try to contain the spill.
In addition, the Defense Ministry sent 500 soldiers and four Navy boats to assist.
Some oil was reported to have reached the coast on the following day.
