Seventy-one million Americans have heart disease, the leading cause of death in the U.S. Heart disease can be predicted by measuring blood levels of the peptide NT-proBNP, released by the heart when under stress.
High peptide level means an 8-fold risk of cardiovascular event.
Other tests for heart risk are calcium scoring, treadmill stress tests and echocardiography.
Short telomeres (DNA strips at chromosome ends) can predict heart disease because they indicate biological ageing.
Frequent childhood abuse increases later risk of heart disease because the body’s inflammation-fighting mechanism is damaged.
A certain gene variant predisposes women to heart disease.
