Auvinen, known to support radical causes, received his gun permit only a few weeks earlier.
He reportedly left a suicide note in which he said goodbye to his family and expressed his anger towards society.
His family has since had to be placed under police protection because of threats.
This shooting spree, which coincided with the Bolshevik Revolution Anniversary, lasted 20 minutes and 69 shells were expended.
Shockwaves were sent through the 5.3 million inhabitants of peaceful Finland.
In recent years, there have been several stabbings in Finnish schools, but only one previous shooting/killing episode of two students in 1989.
