On April 16 2007 a gunman killed 32 people and wounded 29 others at Virginia Tech before killing himself.
This is the bloodiest school shooting in US history.
The gunman opened fire early Monday morning on a Virginia Tech dormitory, killing a man and a woman.
Two hours later the gunman opened fire on classrooms, killing 30 people.
Questions were raised regarding the University’s failure to issue a campus wide alert until the second incident.
University officials defended the decision, stating they were not expecting the second incident.
Virginia Tech classes were cancelled for the rest of the week.
