The jury in the Juan Alvarez murder trial recommended on July 15, 2008 that Alvarez be sentenced to life in prison without parole.
The prosecution had sought the death penalty.
Alvarez was convicted on June 26 of 11 counts of murder and one count of arson in connection with a 2005 Metrolink train derailment that left 11 dead.
Alvarez acknowledged that he had caused the derailment by parking his SUV on the tracks, but he claimed that his only intention was to commit suicide.
Witnesses for the defense portrayed Alvarez as a victim of a violent and abusive upbringing.
