On 18 February 2007, President Bush learned from the Washington Post newspaper of horrific conditions at a Walter Reed Hospital Annex.
Building 18, housing more than 80 soldiers recovering from wounds in Iraq and Afghanistan, was reportedly infested with mold, rot, mice and cockroaches.
A second problem is poor record-keeping which has delayed/denied disability benefits, and hospital releases.
The President demanded an immediate investigation and reparations.
Defense Secretary Gates was concerned the government didn't uncover the problems itself.
He instructed an 8-member review group to provide a report in 45 days, and warned that senior military leaders could be disciplined.
