About 1:42 p.m. Wednesday, Robert A. Hawkins, 19, entered the Von Maur store in Omaha’s Westroads Mall and opened fire with a smuggled-in AK-47 semiautomatic rifle, killing eight apparently random victims before killing himself.
Five people were wounded and hospitalized.
Shoppers and employees dove for cover, fled or locked themselves inside stores.
Hawkins, who left a suicide note, had a troubled past and a history of depression, ADHD, and drug and alcohol use.
He’d recently broken up with his girlfriend, was fired and arrested.
The mall remained closed Thursday.
Von Maur’s owner offered grief counseling to employees and their families.
