Friday morning, a barge under tow struck the Hebei Spirit oil supertanker, puncturing it and causing a 66,000-barrel crude oil leak off the west coast of South Korea near Taean.
Loose tow ropes, which broke in high wind and waves, probably caused the collision.
The leakage was stopped by Friday afternoon.
The South Korean government dispatched four helicopters, dozens of ships and hundreds of soldiers to contain the oil spill by setting up a 5-mile-long boom, scattering dispersants, and pumping up spilled oil and the remaining oil from the damaged tanker.
Oil reached the coastline of nearby Mallipo beach Saturday.
