Heart disease kills 650,000 Americans yearly, and 1 in 3 women.
Southeast and southwest states and Native Americans have the highest rates, with differences due to cultural, not environmental, issues.
Sleep is beneficial and regular naps decrease heart disease risk.
The Reynolds Risk Score, now widely used, improves the accuracy of evaluating women’s heart risk.
It adds parental history of heart attack before age 60 and C-reactive protein measurement to traditional factors of age, smoking habits, systolic blood pressure, total cholesterol, and levels of good cholesterol.
Eating oily fish, taking baby aspirin daily, and exercising helps prevent women’s cardiovascular disease.
