On March 1, 2007, the Food/Drug Administration (FDA) started a broad safety review of children's cough/cold remedies.
They are particularly concerned about use of these drugs by infants.
By September 28th, the 356-page FDA review urged an outright ban on all such medicines for children under six.
Dr. Charles Ganley, a top FDA official said "We have no data on these agents of what's a safe and effective dose in Children." The review also stated that between 1969 and 2006, 123 children died from taking decongestants and antihistimines.
On October 11th, all such infant products were pulled from the markets.
