A 2007 Harvard School of Public Health study of Greek men concluded that napping was more effective than diet or physical activity in lowering heart attacks and other heart disease.
Heart disease is the largest cause of mortality among women, yet some 20 percent of women who suffer from heart disease had no obvious risk factors.
Scientists researching a better way to measure heart disease risk among older women concluded that family history and blood levels of C-reactive protein should be added to existing criteria.
The American Heart Association recommends oily fish and aspirin to help prevent women’s heart disease.
