Police initially stated that Pekka-Eric Auvinen killed seven students and the Principal during the Jokela High School Shooting, but said the next day that the school nurse was also killed.
The motive for the shooting is still open, but Police believe the explanation lies in Auvinen’s Web writings, where he urged revolution and grinned after taking target practice, and in his social behavior.
The shooting spawned rumors of massacres at two more schools.
Police believe Auvinen may have had Internet contacts with an American teenager who had been arrested for allegedly preparing an attack on a Pennsylvania high school.
