Crude oil from the tanker Hebei Spirit began washing ashore on December 8, threatening an ecological and economic disaster on South Korea’s Yellow Sea coast.
As of that evening, oil had fouled some eight miles of beach and was posing a threat to the 181 aquatic farms in the area.
By the following day, over 7,000 military, police, civil servants, and civilian volunteers were working to clean the shoreline, while some 100 boats and five helicopters were trying to clear a 10-mile oil slick at sea.
The remaining crude oil had been pumped out of the holed tanker.
