On Monday, May 12, 2008 at 2:30 p.m.
(0630 GMT), a magnitude 7.8 earthquake struck the densely populated Sichuan Province of China.
It is the worst to strike China since 1976 which claimed 242,000 lives.
Monitoring before the earthquake did not detect any warning signs, and China's past prediction level has been quite high.
Relief offers, donations, and expressions of sympathy have come from Russia, Vietnam, Germany (500,000 euros), Norway (3.92 U.S. dollars), Belgium (250,000 euros), and AIPA (Asian Inter-Parlimentary Assembly).
China itself has allocated 200 million yuan ($29 Million) to this disaster, where 8,533 were reported dead on Monday.
