For years ivory has been in demand for jewelry.
The demand triggered the slaughter of elephants for their ivory tusks.
During 1981 -1988 almost half of Africa’s elephants had been slaughtered.
Trading ivory was banned under the 1989 Convention of International Trade in Endangered Species of Wild Fauna and Flora to halt the killing of elephants.
While the ban worked initially, the effort virtually collapsed in most of Africa.
It was overwhelmed by an exploding demand for ivory in Japan and China and declining support for anti-poaching programs, placing the elephant at renewed risk.
