A massive earthquake measuring 7.8 on the Richter scale rocked China’s Sichuan Province on May 12, leaving at least 12,000 dead and 26,000 injured.
Chinese authorities had detected no warning signs ahead of the quake, China’s worst since 1976.
The Chinese have allocated $29 million for disaster relief, and some foreign governments, including those of Germany, Norway, and Belgium have pledged relief funds.
In addition, the State Ethnic Affairs Commission has allocated $285,000 for aid to ethnic minorities in Sichuan Province.
Rain is forecast for the coming days, which could hamper relief efforts.
