On August 20, 2008, in keeping with the recommendation of the jury in the Juan Alvarez murder trial, Superior Court Judge William Pounders sentenced Alvarez to 11 consecutive life terms in prison without parole.
Pounders called Alvarez a ''remorseless killer''.
Alvarez’s lawyers immediately filed an appeal.
Some members of the jury said after the sentencing that because Alvarez was also found guilty of arson, the felony murder statute had required a first degree murder conviction; otherwise, they might have settled for a lesser charge.
Jurors also cited Alvarez’s abusive upbringing as another reason to afford him a degree of leniency.
