Shortly before 2:30 p.m. on Monday, a 7.8 magnitude earthquake struck southwest China’s Sichuan province.
Chinese earthquake monitoring systems did not detect any warning signs ahead of the quake.
At least 12,000 were killed, and over 26,000 injured.
Thousands are still buried under debris.
Casualties were also reported in parts of nearby Gansu and Shaanxi provinces and the municipality of Chongqing.
China’s State Ethnic Affairs Commission granted 2 million yuan in relief for ethnic minorities affected by the quake.
A number of foreign governments offered China financial aid, including Germany (500,000 euros), Norway (20 million krone), and Belgium (250,000 euros).
