The perpetrator of a shooting rampage at an Omaha mall spent over four years in a series of treatment centers, including two psychiatric hospital stays, group homes and foster care after threatening at age 13 to kill his stepmother.
He became a ward of the state when his parents could not afford treatment.
State custody ended four months before the shooting after agreement by social workers, the court and his father.
He refused drug treatment and, nearing age 19, was deemed ''nonamenable'' for further services, not rehabilitated.
Experts and officials had various views about adequacy of the state services.
