As of May 15, the confirmed death toll from the Sichuan earthquake was up to 15,509, with another 102,103 known to be injured.
Chinese officials fear that there could be as many as 50,000 dead.
The Sichuan provincial government has allocated $95.7 million for disaster relief.
One hundred thousand Chinese soldiers and 1,235 medical teams are participating in search and relief efforts.
A Japanese search and rescue team is scheduled to arrive in Sichuan Province on May 16, and the Chinese Government has accepted offers of search teams from Russia, South Korea, and Singapore.
