Three days after the earthquake, China's Rescue Headquarters confirmed 19,509 dead and 102,103 injured.
They fear the death toll could rise as high as 50,000.
A senior official of Sichuan's Seismological Bureau reported no quake precursors were detected prior to March 12, and therefore no forecast was possible.
To date, no foreigners have been affected by the quake.
Power facilities suffered huge damages, and 26,000 workers are working to repair them.
More than 100,000 Chinese soldiers and police, medical teams and volunteers are in the rescue operation.
One very sad story, 178 children were killed when their school building collapsed.
