On November 8, 2007, an 18-year-old student killed eight people at Jokela High School in Tuusula, Finland.
Five male students, the headmistress, school nurse, and a woman taking a class were the victims.
Twelve others were treated for injuries.
Four days earlier, the gunman Pekka-Eric Auvinen, posted a video entitled "Jokela High School Massacre" on YouTube Website.
Auvinen, who also killed himself, was a brilliant but complex loner obsessed with weapons, and an admirer of Hitler and Stalin.
He brought to school a 22-calibre pistol and 500 rounds.
Finland ranks third behind the U.S. and Yemen in gun ownership rates.
