Over-the-counter cough and cold medicines are ineffective in young children and may harm them.
High doses can lead to arrythmia, hypertension and stroke.
Overdoses can occur easily.
In 2004-5, 1500 U.S. children under 2 suffered serious health problems.
Since 1969, around 50 have died from taking decongestants and 69 died from antihistamines.
Previously, drugs were not tested for children.
The FDA is urged to ban OTC cold products for children under 6 and will consider action in October.
Manufacturers voluntarily withdrew infant cough and cold medicines from the market.
Parental diligence is advised regarding medicating children.
