A study released on Tuesday, February 27, 2007, by wildlife/law enforcement officials concluded that the 1989 ban on international sales of ivory has been overwhelmed in the face of exploding demand for ivory in Japan and China.
Of the approximate 400,000 elephants in Africa, only about 130,000 living in Botswana are protected.
Of the remaining 270,000, about 10 percent are killed yearly for ivory.
Washington University's Samuel Wasser conducted DNA Studies on six tons of ivory seized in 2002, and showed it originated in southern Africa near Zambia.
An aggressive anti-poaching program could now become effective with this DNA support.
