On May 23rd, fourteen African countries supported a 20-year moratorium on ivory trade to allow its elephant population to recover; however, Botswana, Nambia, South Africa and Zimbabwe submitted a contrary proposal saying they worked hard to protect their elephant populations which are now ballooning.
On June 2nd, the international body regulating wildlife trade authorized 60 tons of ivory to be sold to Japan by Nambia, Botswana, and South Africa.
China was rejected because risks of its ivory entering the black market were too great.
Peter Pueschel from International Animal Welfare condemned this saying Japan has numerous loopholes in ivory controls.
