Over 23 metric tons of illegal ivory were seized between August 2005 and 2006 and elephant population in Kenya decreased from 100,000 to about 30,000 between 1989 and 2007.
Responding to a huge increase in poaching and illicit ivory trade, a group of countries led by Kenya wanted the Convention of International Trade in Endangered Species of Wild Fauna and Flora to adopt a 20-year ban on ivory trade in Africa.
Kenya, Botswana and Namibia proposed commercial trade of raw ivory between themselves, South Africa and Zimbabwe, and Botswana sought a sale of 48 tons of raw ivory it possessed.
