The gunman of the Virginia Tech shooting, who killed 27 students and 5 faculty members, was identified as Cho Seung-Hui, a South Korean native and a senior at the University.
Cho had been accused of stalking two female students in 2005 and declared mentally ill by a Virginia special justice.
He was taken to a mental health facility in late 2005 out of concerns he was suicidal.
The shooting incident received international coverage and the shooting details sparked debate over such issues as gun laws, Cho’s state of mind, journalism ethics, and the responsibility of college administrations.
