On March 1st, Major General Weightman, Chief of Walter Reed, was fired by Army Secretary Harvey because the army had lost trust and confidence in him.
Harvey said he would be temporarily replaced by Lieutenant General Kiley, the army's top medical officer.
This suprised Veterans groups because Kiley was Weightman's predessor at Reed, and they thought he too might have been responsible for some of the problems at the complex.
The following day, Secretary Gates announced the resignation of Secretary Harvey, and the army announced Major General Shoemaker as the new head of Reed.
Gates obviously wanted to start anew.
