On October 19th, an FDA panel voted to ban OTC cough/cold products for children under six, but manufacturers said they would fight these recommendations.
And while the same panel voted 21-1 to ban them for infants, the vote for 2-5 year olds was 13-9.
The closer the vote, the more likely the FDA will ignore it.
Also, parents reacted with irritation.
They claim these medicines help the children to sleep, and have been around for years.
The American College of Chest Physicians, on the other hand, state that the medical community has known for years these drugs provide little benefit.
