Children, especially age 2 and under, have suffered serious health problems, including death, after receiving over-the-counter cough and cold medicines,often attributed to accidental overdoses.
Over 1,500 2 yr. olds were affected in 2004-2005.
At least 114 cold medicine-related deaths were documented since 1969.
Adverse effects include arrhythmia, hypertension, stroke and hallucinations.
Pediatricians and public health officials petitioned the FDA to ban marketing cough and cold medicines for children under six.
The FDA has issued a public health advisory, banned future manufacture of hydrocodone products for children, and launched a review of decongestant, antihistamine, cough suppressant and expectorants use for children.
