The gunman was identified as Virginia Tech senior Cho Seung-Hui, 23, from South Korea.
He bought ammunition clips on ebay and chained the doors of Norris Hall before the shooting.
He apparently did a practice run two days earlier.
27 students and 5 faculty members were killed, including G.V.
Loganathan, Walid Mohammed Shaalan, Partahi Lombantoruan, and Liviu Librescu.
Derek O’Dell was shot in the arm.
In 2005 Cho was accused of stalking two female students and was declared mentally ill.
Police searched Cho’s cell phone and school computers to see if Cho communicated with Emily Hilscher, killed in the dormitory.
