Defense Secretary Robert Gates on February 23, 2007, named an independent review panel to investigate outpatient care at Walter Reed Medical Center.
Washington Post newspaper reports revealing poor living conditions of the approximately 700 outpatients housed on or near the Center’s grounds and bureaucratic neglect regarding their treatment had prompted Congress and veterans groups to demand remedial steps.
Some U.S. senators have proposed legislation to raise standards and require inspections of medical facilities.
Congress has scheduled hearings for March 6.
Meanwhile, the Army is taking steps to improve the post’s outpatient housing.
Walter Reed is scheduled to close in 2011.
