Doctors are researching ways to determine a person’s risk of developing cardiovascular disease, the leading cause of death in the United States.
A study found that the length of a man’s telomeres, strips of DNA that cap the ends of chromosomes, can predict his risk of developing heart disease.
Researchers found that statins seemed to eliminate the effects of telomere damage.
A 2007 study found that when the heart is under stress, the blood appears to contain higher levels of a protein known as NT-proBNP and suggested testing for this protein for advance warning of a heart attack.
