A 19-year old man killed eight people and wounded five in a shooting rampage at a mall in Omaha before killing himself.
Police said the shootings appeared random, unprovoked and pre-meditated.
Police used a robot to check his car.
They are investigating what might have motivated the killer.
He had emotional problems, trouble with drugs and alcohol and served jail time for disorderly conduct.
Recently he was kicked out of or left his parents’ home, was rejected by the Army and lost his job and girlfriend.
A suicide note said he was sorry for everything but now would be famous.
