More than 50,000 people are feared dead in Sichuan Province alone after the 7.8 magnitude earthquake rocked the Province.
The confirmed death toll in Sichuan was 19,509 by 4 PM on May 15 2008.
The Chinese government accepted offers from Russia, the Republic of Korea and Singapore to send rescue professionals.
A group of Japanese rescue professionals were the first group of foreign aid personnel scheduled to arrive in SichuanProvince.
More than 100 thousand Chinese People’s Liberation Army soldiers and armed police, 1,235 medical teams, local officials and volunteers were racing the clock for rescue and relief operations.
