In 2005 Juan Manuel Alvarez drove his gasoline-doused SUV onto railroad tracks north of LA and fled.
A Metrolink train hit it and derailed, killing 11 and injuring 180.
Alvarez was charged with 11 counts of murder, one count each of arson and train wrecking, and special circumstance of multiple murders.
He pleaded not guilty, claiming he was attempting suicide and didn’t mean to harm anyone.
LA County DDAs Cathryn Brougham and John Monaghan said he was trying to get attention from his estranged wife.
The jury convicted Alvarez on all charges and recommended life without parole instead of death.
