The Sichuan provincial government provided over 670 million yuan for earthquake relief operations.
Over 25,900 workers work day and night to restore power knocked out by the quake.
By Thursday, power was restored to most parts of Sichuan.
Over 100,000 Chinese soldiers and police and 1,235 medical teams, local officials and volunteers are working in rescue and relief operations.
Rescue professionals from Japan, Russia, the Republic of Korea and Singapore are on the way to the earthquake-stricken area.
By Thursday, 19,509 were reported dead, 102,103 injured, and nearly 40,000 buried or missing.
Officials fear the death toll will exceed 50,000.
