On 7 November 2007 eighteen-year-old Pekka-Eric Auvinem, a student at the Jokela High School in the small town of Tuusula, Finland, went on a rampage at his school, shooting dead seven classmates and the headmistress and wounding a dozen others.
Prior to the shooting he signaled his intentions in a video entitled ''Jokela High School Massacre 11/07/2007'' that he posted on the YouTube Internet site.
The shooting spree lasted twenty minutes.
Following the shooting Auvinem shot himself in the head and died from his injuries.
Police and students were at a loss to explain Auvenen’s motive for the shooting.
