On 12 May 2008 an earthquake with a magnitude of 7.8 struck close to densely populated areas in China’s Sichuan Province.
An initial estimate of 8700 people killed in the quake was later raised to 12,000 people.
Condolences were offered by Russia, the Indonesian Inter-Parliamentary Assembly, Vietnam, Germany, Norway, and Belgium.
Germany, Norway, and Belgium pledged financial aid for earthquake victims.
Chinese authorities did not detect any earthquake warning signs.
Monitoring preceding the earthquake did not detect any macroscopic abnormalities or catch any relevant information.
