As the investigation continues, police concede that they may never know the exact motive for Hawkins’ rampage.
In his suicide note he said he ''just snapped''.
Records show that he spent four years in a series of treatment centers, group homes and foster care after threatening to kill his stepmother in 2002.
However, nothing in his files indicated that he was capable of that kind of violence.
Surveillance videos show that the rampage was planned and so quick that mall security and police had no opportunity to engage the shooter.
Police have ordered extra patrols at other area malls.
