Jurors were moved by Alvarez’s horrific childhood abuse and didn’t believe he meant to hurt anyone.
They convicted him on 11 counts of first-degree murder mostly because of the felony statute on arson, but acquitted him of train wrecking.
Alvarez, 29, was surprised by the decision and smiled.
He acknowledged victims’ blame but didn’t speak.
Some relatives thought life-in-prison would cause Alvarez more suffering than a death penalty and he’d never get out to hurt anyone else.
LA Superior Court Judge William R. Pounders heard the case.
The California Appellate Project will assign a freelance attorney for an appeal.
