As the scandal involving treatment of outpatients at Walter Reed Medical Center expanded on March 1, 2007, Army Secretary Francis Harvey relieved post commander Maj. General George Weightman of his command.
On the following day, Harvey himself was forced to resign by Defense Secretary Robert Gates.
Army Surgeon-General and former Walter Reed commander Lt. General Kevin Kiley was appointed post commander but was replaced a day later, given claims by patients’ family members and veterans advocates that he had long been aware of the problems at the Center.
President Bush called for a thorough review of military medical facilities.
