Studies have found the amount of sleep a person gets affects his or her physical health, emotional well-being, mental activities, productivity and performance.
Lack of sleep has been linked with serious health problems such as an increased risk of depression, weight gain, obesity, cardiovascular disease and diabetes.
Many studies show that getting insufficient sleep can lower your metabolic function, increase sensitivity to pain, and increase mortality.
Sleep deprivation, once considered an adult problem, is now showing up in children.
Treatment options for sleep disorders include meditation, exercise, and bright light and evening activity.
Daytime naps allow the body to recharge.
