The polar bear has become a symbol for the dire effects of global warming as Arctic icepack, critical for its survival, has shrunk.
Environmentalists cite declines in polar bear populations and forecasts of possible extinction in fifty years and argue that only action against climate change can save the bears for future generations.
Conservation groups pressured the Interior Department to deem the bears ''threatened'' in order to force Federal recognition of the science of global warming and to act against it, noting lack of any alternative strategy for preserving the bears’ habitat.
Greenland cut its bear hunt quota.
