Concerning the mutilation charges, Taylor's atrocities alledgely include 7000 citizens of Sierra Leone who had arms, legs, ears and noses removed.
If found guilty, Britian has agreed to imprison him.
The trial will probably last 18 months since the prosecution has 150 witnesses to take the stand.
Surprisingly, or perhaps not, the day the trial was to begin, Taylor dismissed his defense lawyer, and refused to appear at his trial.
In a letter to the judge, Taylor said he would defend himself.
This was the same move used by Yugoslave President Milosevic, who died before his trial could be completed.
