Research has found that sleep deprivation is associated with serious health problems such as depression, obesity, cardiovascular disease and diabetes.
Lack of sleep adversely affects memory function and athletic performance.
Sleep disorders are common in people 60 and over.
Women’s health is at much greater risk than men’s.
Sleep-deprived adolescents are more likely to use alcohol and tobacco.
Sleep-deprived children can exhibit ADHD-like behavioral problems.
Sleep medications are increasingly prescribed for children, but their safety and effectiveness are unknown.
For adults, napping has rejuvenating effects and boosts alertness, performance and productivity.
Other treatment options include meditation, exercise or evening activity.
