On the day after the shoe throwing incident during President Bush’s Baghdad press conference, al-Baghdadia correspondent Muntazer al-Zaidi was hailed by many in the Arab world as a hero.
In Baghdad’s Sadr City suburb, thousands of marchers called for the release of Zaidi, who was still being interrogated by police.
He faces up to seven years in prison for assault on a foreign head of state.
At least 200 lawyers, including some Americans, have offered to defend Zaidi for free.
The incident was an embarrassment to the government of Iraqi Prime Minister Maliki, who condemned it as ''savage'' and ''shameful''.
