The Colorado River, a key water source for seven southwestern U.S. States and Sonora, Mexico, has undergone severe droughts since 2000.
As a result, its two biggest reservoirs, Lake Mead and Lake Powell have become half empty, and may never completely refill.
This emergency has forced Colorado, Wyoming, Utah, New Mexico, California, Nevada and Arizona to forge an agreement in 2007 on how to handle this situation Lake Mead was created in 1935 with the opening of Hoover Dam.
This river supplies water to crop/ranch lands and 25 million people.
The states are now focusing on water conservation regulations.
