Sleep deprivation is especially problematic for teenagers, whose shifted body clocks and increased sleep needs conflict with early school hours and lead to increased disciplinary problems, poorer grades and traffic accidents.
Later school starting times help greatly.
Night-shift workers are at higher risk for developing cancer, reproductive health problems, mental illness and gastrointestinal disorders in addition to the usual array of sleep deprivation-associated problems.
A study found lack of sleep to be associated with an increased risk of developing autoimmune disorders.
Prolonged sleep deprivation has been used as an interrogation technique and has been categorized as torture by defense attorneys.
