Abundant snow during the winter of 2007-2008 and a cool spring combined to increase the flow of the Colorado River, thereby partially refilling Lake Powell and Lake Mead.
From April to September, 2008, officials increased the flow from the Glenn Canyon Dam by 20 percent, and in September, Lake Powell was at its highest level in six years, triggering a large water release.
Earlier, in February, a study relying on historical records and computerized climate models was released by the Scripps Institution of Oceanography, warning that Lake Mead had a 50 percent chance of being unusable by 2021.
