Research continues to provide insight into the links between sleep deprivation and serious health problems such as obesity, heart disease, diabetes, and cancer.
There is compelling evidence that night-shift workers face a significantly increased risk of cancer.
Studies have also determined that too much sleep can negatively affect one’s health.
One study found that oversleeping raised the risk of Parkinson’s disease.
Children, on average, fail to get the minimum recommended amount of sleep, leading to poorer grades and potential disciplinary problems.
Researchers have recommended that school starting times be made later in order to allow children to sleep longer.
