The day after al-Zaidi, the Iraqi television journalist threw his shoes at President Bush, his act of defiance resonated throughout the Arab world.
Thousands of Iraqis demanded his release.
He was hailed as a hero in Syria, and was given an award for courage in Libya.
It was an embarrassment to the government of Prime Minister Nouri Kamal al-Maliki, who termed the shoe throwing ''a shameful savage act'' and demanded an apology from the reporter.
Al-Zaidi was not formally charged immediately, but faced up to 7 years in prison for his act of aggression against a visiting head of state.
