A major interstate highway bridge in Minneapolis buckled and collapsed into the Mississippi during evening rush hour on 8/1/07 killing at least four people and injuring 79 others as 50 vehicles plummeted into wreckage and strong currents.
About thirty people were missing and more victims are expected to be recovered when wreckage is cleared.
An investigation is set to determine cause of the collapse.
Inspection two years ago found structural deficiencies, but did not call for closure or immediate repair.
Federal funds were pledged to help recovery, and governors rushed to start inspections of similar bridges.
Terrorism was ruled out.
