In 2008, water-research experts claimed they didn't expect such insurmountable problems with the river.
They now believe there is a 10% chance Lake Mead could be dry by 2014, or a 50% chance by 2021.
They added, that even if current drought plans are followed, it might not be enough to halt the decline.
Global warming, thought to caused by carbon-dioxide pollution from vehicles, power plants and other industrial emitters, is considered the cause of the nine-year drought.
And without a change in the drought-pattern, some of these states will be forced to go without this water in the future.
