During a December 14, 2008 press conference in Baghdad, a reporter, later identified as al-Baghdadia television correspondent Muntazer al-Zaidi, rose to his feet and hurled his shoes at President George Bush, calling the president a ''dog''.
Both shoes missed their target, and Bush, who was conducting the press conference jointly with Iraqi Prime Minister Nuri al-Maliki, later made light of the incident.
Iraqi security personnel subdued Zaidi and dragged him from the room.
Some of his colleagues speculated that Zaidi’s actions could spell an end to his career.
President Bush was in Baghdad to sign a security agreement with Maliki.
