Michael Vick, the Atlanta Falcons quarterback, pled 'not guilty' in federal court on July 26, 2007 regarding dogfighting conspiracy charges.
Three others were charged with Vick; all four face charges of five years in prison and $250,000 in fines.
The case began on April 25th, when 66 dogs (55 pitbulls) and dogfighting equipment were found on property owned by Vick in Surry County, Virginia.
The indictment also stated that dogs found unfit for fighting were often killed, and that Vick was consulted in one such death.
Vick was temporarily banned from the NFL and his career is in jeopardy.
