An Indonesian volcano, known as ''Lusi,'' has spewed steaming mud since 29 May 2006, submerging four villages, factories, and fields.
It disgorges between 7000 and 150,000 cubic meters of mud daily, forcing 13,000 people to flee their homes.
It erupted from a gas well near Surabaya, East Java operated by Lapindo Brantas, Inc., owned by the Bakrie Group.
British experts who analyzed satellite images of the affected area concluded that the mud volcano was probably a result of drilling.
Bakrie claimed it was a natural disaster.
President Yudhoyano ordered Lapindo to pay 420 million dollars to compensate mud flow costs.
