Prolonged drought, population growth, and the prospect of climate change have compelled officials in the Southwestern states to take measures to manage their water supplies.
Attention has focused on the Colorado River, which supplies water to 25 million people and millions of acres of farm and ranch land in seven states.
Drought, since 1999, has left the largest reservoirs on the river, Lake Powell and Lake Mead, half full.
Federal officials have reached agreement with the states on how water is to be allocated in the event of a shortage.
The pact is to be signed on December 13, 2007.
