A Scripps Institution of Oceanography study indicates that Lake Mead has a 50% chance of becoming unusable by 2021 if the current unsustainable demand for water remains unchanged and if climate change follows current forecasts.
The study claims there to be a 10% chance Mead would be dry by 2014 and a 50% chance that levels would drop too low for hydroelectric power generation by 2017.
Fortunately, above-average snowpacks created this winter and spring have increased the Colorado River’s flow by 20% this summer.
Consequently, Lake Mead’s water levels will not fall as far as expected earlier this year.
