On December 27, 2006, U.S. Interior Secretary, Dirk Kempthorne, announced a proposal to list the polar bear as a threatened species because of sea ice loss.
Kempthorne added his department is not taking a position on why the ice is melting; that's beyond the scope of the Endangered Species Act.
In December 2005, three conservation groups sued the federal government blaming global warming for sea ice melting.
If the proposal is finalized, federal agencies must ensure that anything they authorize, such as oil/gas explorations, commercial shipping etc, will not jeopardize sea ice.
Worldwide Polar bear population is estimated at 20,000-25,000.
