Lake Mead is a primary reservoir of Colorado River water which supplies millions of million people and a million acres of farmland.
An eight-year drought has slowed the river, leaving Mead now half-full.
If current trends continue, Mead might never completely refill.
A newly-signed seven-state accord establishes specific Lake Mead water-levels as triggers for stringent water conservation measures.
New rules allow states to hold conserved water in Mead from year to year.
Arizona restarted a desalination plant to reclaim runoff from farmland.
Las Vegas enacted strict conservation laws, and its casinos and hotels recycle water back to Lake Mead.
