The trial of Former Liberian president Charles Taylor, who faces 11 charges of crimes against humanity, war crimes and violations of international rights, is scheduled for 4 June 2007 in The Hague International Criminal Court (ICC).
Taylor pleaded innocent to all charges.
Taylor’s lawyers demanded more preparation time and resources and threatened to withdraw without them, requesting a new trial date in September.
The request was denied.
Potential defense witnesses for Taylor are refusing to testify at the trial, fearing they would receive UN travel bans and their assets frozen by the UN Security Council.
