In response to the January 12, 2007 RPG attack on the U.S. embassy in Athens, Greek officials, fearing a possible renewal of leftist violence and a potential negative impact on Greek-U.S.
relations, formed a special task force to investigate the incident.
While looking at possible security lapses, police interviewed thousands of persons living in the area and questioned 10 witnesses.
Security cameras at the embassy had captured images of two men and a woman fleeing the scene following the attack, but none were identifiable.
FBI experts arrived in Athens to try to enhance these images.
