Some 500 protestors demanding compensation for homes submerged by a mud volcano blocked a main road junction and railway, causing major traffic congestion.
They refused offers for relocations, demanding cash.
Engineers are tried to plug the mud volcano by dropping hundreds of concrete balls chained together into the well.
Nine months after the volcano began oozing mud the concrete balls calmed the volcano some, but a physicist called for devising a more objective measure of judging the effectiveness of the concrete balls.
The attempt to plug the crater is expected to cost the government $371 million.
