The US Attorney’s office announced that it will seek a second indictment against Michael Vick for gambling on dogfights when a federal grand jury meets next week.
These charges fall under US racketeering law and carry a potential 20-year prison sentence.
A gambling conviction would end his career in the NFL which prohibits any association with gamblers and gambling.
Because of the potential new charges and the news that his remaining co-defendants are scheduled to enter guilty pleas this week, Vick’s attorneys are trying to negotiate a plea deal that would limit his prison time and save his NFL career.
