Saturday, the Mississippi’s murky, swirling waters hampered recovery efforts, forcing divers to suspend operations to recover bodies they could see trapped below in the I-35W Bridge wreckage.
The death toll is now five, with at least eight still missing.
Of the roughly 100 injured, 24 remain hospitalized, with five in critical condition.
The Red Cross set up a site to offer counseling.
President Bush toured the area Saturday and promised to expedite federal aid to rebuild the bridge.
Minnesota officials were warned as early as 1990 that bridge was ''structurally deficient''.
They responded by implementing patchwork fixes and stepped-up inspections.
