On June 4, former Liberian president Charles Taylor will be tried by the UN-backed Special Court for Sierra Leone in The Hague, where he’s been held since last year.
He was the single most powerful figure behind a series of civil wars in Liberia and Sierra Leone from 1989-2003.
Taylor pleaded innocent to 11 charges of war crimes, crimes against humanity, and violations of international human rights.
He is specifically accused of arming and training rebel groups which murdered, enslaved, raped and mutilated thousands of civilians in Sierra Leone’s bloody 10-year civil war.
He faces a life sentence if convicted.
