A US study raised questions about vitamin D and cancer.
It found no sign that vitamin D lowered the overall risk of dying from cancer except for significantly lowering the risk of death from colorectal cancer.
The study cautioned that the issue is far from settled and advised people not to assume vitamin D is a cure-all and consume large doses.
Recent research indicating vitamin D may have multiple health benefits has ignited a debate over whether federal guidelines are insufficient, leaving millions vulnerable to diseases.
Leading experts caution against recommending large doses of vitamin D prematurely.
