Polar bears depend on sea ice to travel, hunt, and give birth, but ice is melting due to global warming caused by industrial emissions.
Arctic sea ice has declined 20 percent.
Bear population declined 22 percent.
Pregnant bears are digging snow dens on land instead of sea ice.
Petroleum activities disturb bears’ feeding and reproduction.
Beloved polar bears could disappear.
Greenland cut its polar bear hunting quota.
Environmental groups sued to force a ''threatened'' designation requiring the U.S. to create a polar bear recovery plan.
Government balked because it would mean limiting global warming, and prevented scientists from speaking freely.
