The US embassy in Athens reopened Tuesday, four days after the attack.
Greek authorities formed a special task force to investigate.
They identified the weapon used as a Chinese-made RPG7 of Russian design.
Police are reviewing witness accounts, examining forensic evidence collected at the scene, and investigating possible security failures.
FBI experts in Athens are working closely with the Greek anti-terrorist squad and trying to enhance security video recordings in order to identify possible suspects.
Greek police are still investigating to verify the Revolutionary Struggle’s claim of responsibility for the attack.
So far, no arrests have been made.
