Two new vitamin D studies, published by Moores Cancer Center, University of California, San Diego, in February 2007, revealed new prescriptions for preventing breast and colorectal cancers.
Both studies found that taking 2000 international units of vitamin D3 daily, and a little sunshine could cut breast cancer cases by half and colorectal by two-thirds.
However, there are detractors.
Harvard's Dr. Edward Giovannucci, said "It's a very small study" and "I don't think it's the last word".
Also, Dr. Michael Thun of the American Cancer Society favors keeping the dosage level at 200-600 IUs, stating 2000 units is potentially dangerous.
