Co-defendants Purnell Peace and Quanis Phillips scheduled plea agreements before Judge Henry Hudson.
Vick will likely make a plea that limits his prison time but is waiting to hear from the NFL about consequences to his career.
If he pleads guilty he faces a year in prison.
Federal prosecutors will seek a superseding indictment that includes an additional charge under the RICO statute and potentially 20 years in prison.
NFL commissioner Roger Goodell appointed Eric Holder to investigate charges against Vick and advise the league.
The Southern Christian Leadership Conference backed off its vow to honor Vick at its convention.
