Charles Taylor’s war crimes trial began June 4 without him present.
Instead, he sent a letter in which he complained of insufficient resources to defend himself and dismissed his attorney.
Presiding judge Julia Sebutinde of Uganda rejected Taylor’s claims, directed an assistant attorney to take over and continued the proceedings.
Prosecutors plan to call 150 witnesses.
Taylor, the first African leader to be tried for war crimes in an international tribunal, allegedly orchestrated and funded rebels’ unspeakable atrocities in Sierra Leone in exchange for ''blood diamonds'' illegally mined there.
If convicted, Taylor would serve his remaining years in British jail.
