The Taylor trial will begin with the prosecution’s four-hour opening statement, and then will adjourn until 25 June 2007, when it will hear the first of 150 scheduled prosecution witnesses.
Once the prosecution rests its case, in about a year, the defense will give its opening statement.
The trial is expected to last 18 months.
Most of the prosecution witnesses will testify under pseudonyms, although the defense will know their identity.
Some will be eligible for relocation after the trial.
If convicted Taylor must be imprisoned for a specific number years and will serve the time in a British jail.
