Vitamin D serves many purposes in the human body.
A deficiency of the vitamin has been linked to several diseases.
Studies have revealed that raising vitamin D levels may help prevent colorectal cancer by two-thirds and breast cancer by half.
Another study found that Vitamin D lowers the risk of several types of cancer by 60 percent in older women.
Vitamin D is critical for the absorption of calcium and when the body doesn’t get enough it draws calcium from bones, reducing bone density.
Some medical groups are urging people to increase vitamin D intake to reduce cancer risks.
