The closer researchers examine sleep, the more they learn about the benefits of sleeping.
One study found that sleep deprivation is associated with enhancement of pro-inflammatory processes in the body.
The findings suggest that loss of sleep, even for a few hours during the night, can prompt a person’s immune system to attack healthy tissue and organs, increasing the risk of autoimmune disorders.
A study reported that 15 million American children are affected by inadequate sleep, leading to poor grades, moodiness and depression.
Sleep deprivation among teenagers creates a negative spiral of fatigue, emotional instability, poor decision-making and risky behavior.
