In May 2008 a gas drilling site in East Java, Indonesia, began spewing steaming mud, triggered by Lapindo Brantas Inc. drilling through overpressured limestone without sufficient precautions.
Social Minister Aburizal Bakrie, whose family owns Lapindo, blamed a distant earthquake.
By February mud had submerged villages, industries and fields near Surabaya and left 15,000 people homeless.
Thirteen died when a nearby underground pipeline ruptured.
Lapindo is ordered to pay $420 million in damages.
Mud is being channeled into the sea, although it could damage the marine ecosystem.
Concrete balls will be dropped into the volcano to attempt to slow the flow.
