A rocket propelled grenade was fired at the U.S embassy in Athens on the morning of January 12, 2007, causing minor damage to the building but injuring no one.
An extreme leftist group, Revolutionary Struggle, subsequently claimed credit for the attack, raising Greek fears of renewed violence by far-left militants.
The incident was reminiscent of previous attacks by the November 17 group, which was blamed for the deaths of 23 persons before being eradicated in 2002.
U.S. officials called the attack serious but saw no evidence of international involvement.
An FBI team was being sent to aid in the investigation.
