On 14 December 2008, during a news conference with Iraqi Prime Minister Nuri-al-Maliki, Muntazer al-Zaidi, an Al Baghdadia channel television reporter, threw his shoes one by one at visiting President George W. Bush and called him a ''dog'' in Arabic.
When throwing the second shoe he yelled ''It is a farewell kiss, dog''.
Security personnel wrestled the reporter to the floor and into the hall as he screamed.
President Bush ducked and missed being struck, laughing off the incident and declaring it didn’t bother him.
Soles of shoes are considered the ultimate insult in Arab Countries.
