Federal prosecutors indicted NFL quarterback Michael Vick and three others on federal interstate dogfighting conspiracy charges connected with alleged operations at his home in Surry County, Virginia.
The charges stem from an April drug search which turned up 66 dogs and dogfighting equipment.
If convicted, the defendants face up to five years in prison and $250,000 in fines.
Vick and his co-defendants pleaded not guilty.
However, under a plea deal, one changed his plea to guilty and signed a statement attesting that the charges are ''true and accurate''.
The trial for the remaining three is set for November 26.
