The US embassy in Athens was struck by a shoulder-launched rocket-propelled grenade shortly before 6:00 a.m. Friday.
The rocket was probably fired by a Russian-made launcher from a nearby construction site.
There were no casualties and only minor damage to the building.
Police cordoned off streets around the embassy following the attack.
Greek authorities are investigating claims of responsibility by the left-wing terror group Revolutionary Struggle.
State Department and Greek authorities are cooperating in the investigation of what they believe to have been an act of domestic, rather than international, terrorism.
FBI forensic experts will go to Athens to assist.
