By August 14th, the three others charged with Vick in Richmond changed their not guilty pleas and entered plea agreements.
One of Vick's attorneys said he was surprised by the plea deals and didn't see it coming.
Additionally, the prosecutor said he was seeking to bring racketeering charges against Vick, which could result in a 20-year sentence.
According to Atlanta/Virginia newspapers, as of August 15th, Vick's lawyers reportedly were trying to negotiate a plea with federal prosecutors that might limit his jail time, and allow him to return to professional football.
Perhaps,it's time for Vick to take a knee.
