Former Liberian President Charles Taylor will go on trial at a UN-backed court in the Netherlands on June 4, 2007.
He was the single most-powerful figure behind civil wars in Liberia and neighboring Sierra Leone during 1989 and 2003 which left 400,000 dead.
The former warlord-turned-president has 11 charges pending: terrorism, murder, rape, sexual slavery, mutilation, and recruitment of child soldiers.
Taylor, pleading innocent, allegedly provided rebels with arms/ammo, alcohol, drugs/cigarettes in exchange for diamonds smuggled out of Sierra Leone.
He was flown to the Netherlands in 2006 amid fears his trial in Sierra Leone could trigger new unrest there.
