A U.S. National Cancer Institute study published October 30, 2007, found no sign that vitamin D lowers the overall risk of dying from cancer.
One exception noted was that people with more vitamin D had a significantly lower risk of death from colorectal cancer.
Johanna Dwyer of NIH cautioned that the public should not assume that vitamin D is a magic bullet and consume high amounts.
A University of Toronto study published in the U.S. on May 15, 2008 stopped short of recommending taking vitamin D to reduce the risk of breast cancer, saying more research must be done first.
