Various governments, institutions, and environmental groups are taking steps to preserve world turtle populations.
Much attention is focused on sea turtles, but other species of turtles are also endangered.
Cambodian wildlife officials are trying to protect the habitat of a recently discovered population of ultra-rare Cantor’s giant turtles.
Pakistan has organized patrols to monitor beaches where green sea turtles nest, and Taiwan bars tourists from designated beach areas during the nesting season.
Indonesia has prosecuted turtle poachers who violate its conservation laws.
In the U.S., Texas has re-established a Kemp’s ridley nesting area on Padre Island.
