The investigation into the Glasgow attack, believed to be al-Qaida-associated, progresses at breakneck speed.
Police recovered a trove of evidence from vehicles and surveillance videos.
They searched several houses around Glasgow and central England.
By Monday, seven suspects were in custody.
At least five suspects are foreign nationals, one of whom is a medical doctor.
By Sunday afternoon, Glasgow and Liverpool airports reopened under tight security.
Security was stepped up at British airports and train stations, and spot checks of cars began around the country.
Part of London’s Heathrow Airport was temporarily closed following a suspicious package report.
