Armed Somali pirates hijacked the largest vessel yet, Saudi-owned oil tanker Sirius Star, 10am Saturday morning off the coast of East Africa as it headed toward the Cape of Good Hope.
The hijacking, likely for millions in ransom, occurred hundreds of miles out in the Indian Ocean, far south of the Gulf of Aden area patrolled by international warships.
Tuesday the ship was anchored off the Somali piracy hub port of Eyl, near the coastal town of Haradhere.
Owner Vela International Marine Ltd. is working to free the ship and its international crew of 25, including two Brits.
