Governments and medical authorities around the world are undertaking to formulate regulations covering organ transplants.
Their aim is to encourage organ donations while preventing any black market trade in organs.
The need for regulations has become apparent to lawmakers in China, Russia, the Philippines, and Zimbabwe.
In China, for instance, there is an enormous gap between the number of persons needing replacements for failed organs and actual donations.
Although the Chinese deny it, it has been alleged that organs have been harvested without permission from prison inmates.
Even in the U.S., there are ethical and legal questions despite existing regulations.
