Britian raised its terrorism threat assessment to its highest level on Saturday, June 30, 2007, after two men slammed a Jeep SUV into depature doors at Glascow Airport.
Only one day earlier, a double car-bomb plot was foiled in London.
One of the two men arrested in the Glascow attack was in flames as he fought with police shouting "Allah, Allah," an eyewitness said.
He has since been hospitalized and his accomplice arrested.
Two cars packed with explosives were discovered in London on Friday parked near Piccadilly Circus.
British Prime Minister Brown praised the efforts of the emergency response teams.
