On 12 December 2008 Bernard Madoff Investment Securities collapsed hours before Madoff's arrest for stealing some $50 billion from investors in fraudulent financial moves.
For decades Madoff appeared to be remarkably successful, but when investors requested the return of about $7 billion in principal at the end of 2007, Madoff confessed his business was a giant Ponzi scheme.
Among those duped were top US investors, large European banks, and a Tokyo bank.
Despite red flags, the Securities and Exchange Commission was taken by surprise and hedge fund companies kept promoting Madoff to other funds and individuals.
