An estimated 27 million HIV-infected persons live in sub-Saharan Africa.
Scientists, researchers, and medical personnel are seeking not only cures for AIDS, but also strategies for prevention.
Preventive measures are far less expensive than AIDS treatment.
One study found that a drug used to treat genital herpes reduced levels of HIV in the blood by 70 percent.
Another study looked at the use of microbicides by women, who account for over half of all AIDS infections in Africa.
Meanwhile, successful trials conducted in several countries showed that male circumcision more than halves the risk of HIV infection.
