An Indonesian ferry boat with some 600 persons on board sank on December 29, 2006 as it neared the end of a two day journey from Borneo to Java.
Bad weather was thought to be the cause of the sinking.
By January 3, around 200 people had been rescued from the sea by naval vessels and fishermen, and an unknown number of bodies had been recovered.
Some survivors in life rafts had been spotted by aircraft, and food and water was dropped to them, but continued bad weather was hampering rescue attempts.
Officials planned to continue the search for survivors.
