As of January 8, 2007 some 245 survivors of the December 29 Indonesian ferry sinking had been picked up, but only 10 bodies had been recovered.
Fourteen survivors were found in a life raft approximately 300 km. from where the ferry was thought to have sunk, prompting officials to expand the search zone further east.
Survivors thought hundreds of passengers had probably gone down with the ferry.
The exact site of the sinking was not known.
Bad weather and the existence of many sunken ships on the ocean floor were impeding the search for the wreck.
