Because Taiwan’s coral reefs were considered among the healthier in the world, in February 2008 United States researchers joined island scientists in studying Taiwan’s undersea formations in hopes of saving coral reefs worldwide.
A report released in December 2008 warned that Taiwan’s coral reefs were under severe stress or had been heavily damaged.
The National Oceanic and Atmospheric Administration (NOAA) reported that nearly half of coral reef ecosystems in the United States are in barely passable condition due to global warming and pollution.
To lessen the threat NOAA suggested curbing emissions of carbon dioxide and other greenhouse gases.
