Wall Street investment firm owner Bernard Madoff was arrested for securities fraud and stealing $50 billion.
He told employees and family that he was running a giant Ponzi scheme.
He was freed on $10 million bail.
His firm is cooperating with government.
SEC investigators and forensic auditors are investigating what Madoff did with the money and are looking at banks and money managers who steered clients to Madoff.
Madoff claims he acted alone.
Staffers for federal court-appointed receiver Lee S. Richards 3d are determining what assets can be preserved for investors.
Lawyer Mark Mulholland filed a class-action lawsuit against Madoff.
