Already a dry country, China faces severe water shortages as increased evaporation, due to higher temperatures, reduces supply even as ever more is needed for a growing population and expanding industrial and agricultural production.
River levels dropped sharply to record lows in 2007, after bad droughts, hurting fish stocks, navigation and drinking water supply and worsening pollution.
Extra water release from the huge Three Gorges Dam provided some temporary relief.
The government plans quotas and other measures to cut average consumption, efforts to recycle industrial water and construction of desalination plants along the coast.
