Wall Street financier Bernard Madoff was arrested on December 11, 2008 and charged with securities fraud after he allegedly confessed to his sons that he had swindled investors out of $50 billion through a giant pyramid scheme.
A federal judge placed Madoff’s company in receivership the following day.
Individual investors, charities, hedge funds, and various financial institutions were among the fraud victims.
Banks and financial authorities across Europe were urgently trying to determine the scope and impact of losses.
Spain’s largest bank, Santander, believes it may have lost over $3 billion.
Madoff was freed from jail on $10 million bond.
