Following Madoff’s confession of fraud to his two sons, they reported the confession to the FBI.
Two agents were dispatched to Madoff's apartment to interview him.
Four days later a federal judge appointed Irving Picard as trustee to liquidate Madoff’s firm.
Bernard Madoff insisted that no family member was involved in the Ponzi scheme and Federal investigators found no evidence of family member involvement.
Madoff’s two sons, Andrew and Mark, and his brother, Peter, held senior positions at the firm and appeared shocked when the fraud was disclosed One of Madoff’s sons had considerable money invested in accounts Madoff managed.
