On 15 March 2007 a giant crane separated from the side of a skyscraper under construction and smashed into a block of residential buildings, demolishing the buildings, killing four construction workers, and injuring 24 others.
Nineteen of the 44 stories of the crane had been erected and it was to be extended, when a piece of steel fell and sheared off one of the ties securing it to the building.
The crash and huge response, which involved more than 100 firefighters and numerous city and state agencies, created traffic congestion and temporarily disrupted subway and bus service.
