The Securities Investor Protection Corporation (SIPC) liquidated Madoff’s firm.
U.S. District Court for NY’s Southern District appointed Irving H. Picard as trustee and Baker & Hostetler as Picard’s counsel.
Madoff promised steady returns and gained investor confidence through financial-planning firms and his club and board memberships.
His scheme collapsed in the global financial crisis.
Sons Andrew and Mark turned him in.
Madoff confessed to the FBI, who arrested him.
No evidence surfaced that Madoff’s family helped him.
Employee Frank DiPascali worked most closely with Madoff.
SEC investigations of Madoff in 2005 and 2007 found no major problems and were closed.
