China has introduced new measures to counter water shortages which worsened in 2007 because of low rainfall and increasing temperatures.
Shortages have forced cuts in industrial production, costing income, jobs and tax revenues.
Water is being trucked to some areas, new waterworks constructed, wells dug, pools built to capture rainfall and artificial rainfall launched.
Some areas have diverted water from reservoirs and a mammoth south-to-north water diversion project is underway to provide water to Beijing and other cities.
Farmers have turned to drought-resistant crops.
Government officials recognize a critical need to build ''a water-saving society,'' changing many everyday practices.
