Coral are sea animals whose skeletons make up reefs that form the backbone of an ecosystem supporting undersea life.
Corals reefs have been dying globally due to environmental disruptions and are at risk of extinction.
In 2007 the United States submitted a request to the UN endangered species trade regulation agency to control the trade in coral.
The agency agreed to regulate sales but removed the restrictions days later.
Scientists in Florida are nursing tiny coral fragments in a lab and transporting them to coral reefs and conservation groups are working on global reef restoration efforts.
