The World Health Organization approved male circumcision as one of many means to reduce HIV infection.
Over 20 years, 5.7 million new HIV cases and 3 million deaths could be prevented.
Ugandan health facilities have been inundated with requests.
Malawi is debating whether to adopt male circumcision as policy.
The Gates Foundation is funding a new trial to see whether circumcised HIV-infected men are any less likely to infect their female partners.
Madagascar received $7.5 million in UN assistance for its anti-HIV/AIDS plan.
South Africa is implementing a new UN-approved five-year program designed to halve the incidence of HIV infection.
