The Sirius Star was seized in a 16-minute attack by pirates in two speedboats, armed with rifles and rocket-launchers.
Their group operates from mother ships south of the Gulf of Aden.
The vessel and its crew continue to be held through Thursday.
The pirates demand $25 million ransom, with a 10-day deadline.
According to media reports, the ship's owners are negotiating with the pirates.
The owners remain tight-lipped on the subject.
Saudi Arabia will join an international Red Sea area anti-piracy initiative.
Russia called for an international ground military operation in the region and plans to send in more warships.
