Scientists warn that up to half of the world’s coral reefs could disappear by 2045.
Reefs are vital ecosystems which support diverse undersea populations, protect shores from storms and generate billions in trade and tourism dollars.
They are threatened by pollution, overfishing; climate change, coastal development, deforestation, unrestricted tourism; destructive fishing methods, over-harvesting for commercial trade and ship groundings.
Conservation efforts include partnerships between conservation groups and the tourism industry and the establishment of well-managed protected areas.
Florida is managing underwater coral nurseries.
The UN CITES convention placed 26 coral species under protection, but reversed the decision two days later.
