Coral reefs are indicators of overall ocean health.
Of the 700 coral species, 32.8% are endangered.
A quarter of all marine species need reefs to live and grow, and 40% of commercially-caught fist need them to breed.
Reefs worldwide have suffered from bleaching, caused by rising ocean temperatures.
According to NOAA, the Caribbean region has lost at least half of its corals since 2005.
Elkhorn and staghorn corals were the first corals to be listed as threatened under the Endangered Species Act.
Mushroom coral along the shores of Taiwan’s Green Island are endangered by human activity and algae growth.
