British authorities claimed that the above terrorist incidents were linked to al-Qaida.
In all, seven people have been arrested.
One was a 26-year-old medical doctor, Mohammed Asha, of Iranian-Kurdish descent, who had offices at the Royal Alexandra Hospital near Glascow.
Also, one of the two men involved in the Glascow Airport attack is said to have worked at that hospital.
Another report said an Iraqi Doctor, Bilal Abdulla, was one of the two men involved in the Glascow attack.
Sources said propane cylinders found in all three cars were almost identical, lending further credence that the two attacks were connected.
