In recent years, countries around the world have been trying to find ways to make organ-transplant procedures more effective and legitimate.
In some countries, such as China and Russia, organ trafficking has become a problem.
China's military hospitals reportedly have turned to selling organs to make up for government funding cuts, with the organs taken from unwilling donors such as prisoners.
Much of the trade in human organs takes place on the black market.
In the Philippines, 3000 people sold their kidneys for between $1500-2500.
In smaller countries like Zimbabwe, patients have to go abroad because proper resources don't exist.
