6,700 of 95,300 Americans awaiting an organ die yearly.
Recent U.S. legislation approved North Carolina’s prison sentence shortening for organ donation, eases giving live organs to non-family members (legalizing paired kidney donations), and sets new standards for transplant volume and survival rates that will cause some transplant programs to close.
Some employees get extra leave for organ donations.
More organs are becoming available as doctors increase harvesting after the heart stops rather than waiting for brain-death, and through liver-splitting.
China banned organ trading and ruled that organ donors must be 18 and use of executed criminals’ organs must be voluntary.
