The ferry Senopati Nusantara sank off the coast of Java late Friday, 10 minutes after dropping anchor and being pounded by heavy waves for 10 hours.
It was before midnight near the end of its two-day Borneo-Semarang journey.
Bad weather was blamed.
Around 600 were on board the ferry licensed to carry 850.
Many were trapped in lower decks.
By Monday night fishermen and navy teams found 218 survivors, in lifeboats, clinging to debris, or on beaches.
Helicopters located 3 life rafts with 30-40 survivors but heavy weather prevented picking them up so they dropped food and drink to them
