All seven of the world’s species of sea turtles are endangered and face serious threats from commercial fishing nets and pollution, and some species are hunted for their meat or their shells.
Some countries have passed laws to protect the turtles.
In April, 2007, Malaysian courts sentenced two groups of Chinese turtle poachers to eighteen months in prison for taking protected hawksbill and green turtles in Malaysian waters.
In Mexico, environmentalists have joined with Mexican authorities to protect sea turtles’ eggs from poachers and predators.
Scientists say that the loss of sea turtles could have unforeseen, even catastrophic, consequences.
