At 2:20pm Saturday, a 205-ft.
crane separated from the side of a high-rise condominium under construction at 303 E. 51st Street in Manhattan, killing 4 and injuring 24.
Two construction workers and a woman visitor are missing.
The crane damaged 5 residential buildings and destroyed a building at 305 E. 50th Street, including the Fu Bar.
A shelter was established in a school.
While building the crane higher, a steel collar holding it to the building fell and sheared off a lower collar, creating an imbalance.
Investigations focused on the hoists and nylon straps that held the collar in place.
