Other ill effects of China's water shortage have included huge herds of livestock languishing for water, farmland left idle, and closure of plants which are high pollutant generators.
In Ankang City, 16 high-profit-enterprises have been shutdown, leaving 3000 people without jobs.
In some villages, ponds have dried up, and people have to travel to find water.
Since some municipalities have ordered hydropower plants not to store water for electricity generation, restrictions on power usage have imposed temporary blackouts of large stores, hotels, industrial manufacturers and civilian homes.
The U.N. predicts water shortages will affect two-thirds of the earth by 2025.
