Lawmakers and the medical community are seeking ways to increase the supply of organs available for transplant without overstepping ethical bounds.
Under a South Carolina plan, prison inmates who donate organs could have their sentences reduced.
In March, 2007, the U.S. House of Representatives passed a bill making it easier for living donors to give away a kidney and legalizing ''paired'' kidney donations.
Liver-splitting techniques and the ''donation after cardiac death'' approach to organ harvesting have markedly increased the number of organs available to those in need.
New federal standards for transplant programs were unveiled in March.
