A worldwide assessment of corals has determined that nearly 30 percent are threatened with extinction.
Loss of coral reefs could profoundly affect more than 500 million subsistence fishermen who depend on coral reef ecosystems for their livelihood.
According to NOAA officials, 40 percent of all fish caught commercially breed in coral reefs.
In the U.S., research on coral reef depletion has expanded dramatically, and large-scale conservation measures are being taken or are contemplated.
Meanwhile, NOAA has expanded its worldwide Coral Reef Watch network and is using satellites to monitor ocean temperatures, to which corals are extremely sensitive.
