The Securities Investor Protection Corporation announced on December 15, 2008, that it was liquidating Bernard Madoff’s investment company.
Madoff’s arrest on charges of securities fraud raised serious questions about the U.S. financial regulatory system.
The SEC had twice conducted inquiries of Madoff but had detected no wrong doing despite the existence of certain warning signals.
It was not clear to investigators how one person could commit such massive fraud, but there was no evidence that any of Madoff’s family members was involved.
Meanwhile, leading banks in the Netherlands, France, and the UK were admitting significant exposure to potential losses.
