Corals worldwide are dying.
Researchers believe that 25 percent of the world’s coral disappeared over the last 25 years, and that another 25 percent could die within the next 10 years.
Among the reasons for corals’ decline are excessive harvesting, pollution, over-fishing, diseases, and climate change.
Because of their ecological importance, researchers are trying to devise ways to restore damaged reefs, including planting farm-grown corals on depleted reefs.
The United States has declared some varieties of coral endangered species and has taken the lead in seeking international oversight of the trade in pink and red corals in particular.
