Black market organ trafficking has occurred in Russia, China and the Philippines.
China’s military harvests organs from Falungong prisoners for sale to foreigners.
Canadian recommendations include laws against travel to China for forced-donor transplants, and discontinuing anti-rejection drug sales to China and follow-up care for Chinese organ recipients.
Zimbabwe and the Philippines are writing transplant regulations.
A Kaiser Permanente transplant program closed because of inefficiencies.
More organs could become available through South Carolina’s plan to shorten prisoners’ sentences in exchange for organ donations, mismatched blood type organ transplants for infants, and promotion of brain-death idea for organ donation in China.
