On Saturday, March 15, 2008, a crane accident occurred at New York's 2nd Avenue and 51st Street.
The crane mounted to a skyscraper under contruction split into pieces falling upon a 4-story-brownstone building, demolishing it.
Parts of several other buildings were also hit.
Police announced that four construction workers were killed, twenty-four people injured, including 11 first responders, and three were missing.
City officials reported that about 250 cranes were in operation at the time of the accident.
Mayor Bloomberg said an investigation is underway to see whether human or mechanical error was involved, or if procedures just aren't adequate.
