About 60% of all HIV patients live in sub-Saharan Africa, where last year 2.8 million people became infected and 2.1 million died.
Life expectancy in Malawi is now 35 because of HIV/AIDS.
Over half of new HIV infections in Africa involve women and girls.
As many as 31% of HIV patients suffer from HIV-related dementia.
Scientists are conducting numerous studies in Africa seeking to prevent HIV infection.
Tests of one antimicrobial vaginal gel were halted in failure.
The drug valacyclovir shows promise.
Male circumcision, a difficult measure to implement, has proved to reduce the risk of HIV infection by half.
