On March 22, 2007, U.S. federal health officials unveiled new standards that hopefully will result in a decrease of patient deaths and failures of transplanted organs.
This comes 18 months after a series of scandals in California exposed serious gaps in the nation's transplant system.
In the U.S. some say the transplant process can interfere with the patient dying peacefully, surrounded by loved ones, and denies families sufficient time to grieve.
This is because once a transplant decision has been made, teams position themselves nearby so that shortly after the donor's heart stops beating, the transplant process can get underway.
