Around 3:15 p.m. Saturday, two men slammed a burning SUV into Glasgow airport’s main terminal doors, turning the vehicle into a lethal fireball.
Authorities immediately closed and evacuated the airport and raised the national terrorism threat level to ''critical,'' meaning a further attack was imminent.
The attackers, one badly burned, were arrested.
Shortly after the attack, authorities closed Liverpool airport and blocked vehicle access to New Castle, Edinburgh and Blackpool airports.
Early Sunday, counter-terrorism officers announced the arrest of two more people in connection with both the Glasgow airport attack and Friday’s foiled double car bomb plot in London.
