Rescuers dug through debris for three people still missing in the rubble and continued to remove pieces of the crane and piles of debris from the damaged buildings left when a construction crane collapsed in Manhattan.
Recovery workers used thermal imaging devices and sniffer dogs in search for those missing after the accident.
They discovered three more bodies that included two construction workers and a tourist visiting New York, bringing the total people killed to seven.
Investigators believe a piece of nylon webbing may have failed while hoisting a six-ton piece of steel, causing the failure.
