The three missing bodies were found on Monday, March 17th, in the demolished Brownstone Building.
Two were construction workers and the third, a female tourist from Florida, bringing the death-total to seven overall.
While this accident will cost millions, investigators now suspect that a $50 piece on nylon webbing may have failed while hoisting a six-ton-piece of steel.
Bradley Closson of Craft Forensic Services, California, said: "That's definitely a tensile failure".
However, Buildings Commissioner Patricia Lancaster said the nylon strap is just one theory.
Residents in 300 apartments in seventeen buildings were evacuated as a result of the overall accident.
