At 10 a.m. Saturday morning, Somali pirates hijacked the Saudi-owned super tanker Sirius Star in the Indian Ocean off the east coast of Africa.
Its 25-member crew included Croatian, British, Philippine, Polish and Saudi Arabian nationals.
By Tuesday, the vessel was anchored off the Somali piracy hub port of Haradhere (Xarardeere), likely held for ransom.
Considered Somalia's biggest economy, piracy brings in million-dollar payouts.
The ship's owner, Dubai-based Vela International Marine Ltd., established response teams which are working to free the ship and crew.
The EU is planning to launch anti-piracy patrols off Somalia beginning next month.
