On 3 January, 2007, a report from Beijing stated that global warming is seriously impacting China's ecological, social, and economic systems, and some of this damage will be irreversible.
And while concerned about global warming, China says it lacks the money/technology to reduce its greenhouse gas emissions.
The most serious of these issues is water shortages.
The Yangtze River, the nation's largest, is at its lowest level in 100 years.
This shortage is affecting fish and migratory bird survivals, crop productions, availability of drinking water, and numerous maritime shipping problems.
China does plan to cut water consumption 20% by 2010.
