A second co-defendant in the O. J. Simpson armed robbery case agreed in October, 2007, to testify against Simpson, who had pleaded not guilty to all charges.
The trial, which eventually lasted three weeks, began on September 8, 2008 in Las Vegas.
Simpson and one co-defendant, Clarence Stewart, were tried together, and both were found guilty of all charges.
Sentencing took place on December 5, with Simpson and Stewart receiving 15-year prison terms with a possibility of parole in five years.
Both defendants’ lawyers vowed to appeal.
