Former football star O. J. Simpson was arrested on September 16, 2007 and charged with armed robbery at a Las Vegas hotel three days earlier.
According to reports, Simpson and five other men, two of whom were armed, entered the room of two sports memorabilia dealers and took items worth possibly $100,000.
When questioned by police, Simpson said he was retrieving items that belonged to him.
Simpson and the others were eventually charged with ten felonies each, including armed robbery and kidnapping.
One of Simpson’s co-defendants agreed in October to testify against Simpson.
Arraignment was set for October 23.
