Flooding in Bangladesh had, as of August 6, 2007, damaged crops on over 5 million acres of farmland, displaced or marooned up to 8 million people, and claimed 120 lives.
The government was operating 614 shelters in the northern part of the country.
In some places, food was being distributed by boat.
The Bangladesh Government announced that it would welcome ''cooperation'' but that it did not require foreign aid.
Nevertheless, Britain allocated $2.5 million for relief efforts, and Germany about $685,000.
Further north, in India, some 7 million people had been affected, with at least 120 killed.
