So far, ongoing Bangladesh monsoon floods have claimed 120 lives and affected 8.1 million people in 38 districts.
They’ve destroyed nearly 600,000 houses, damaged 90,000 houses and caused colossal loss of crops and infrastructure.
Media reported a scarcity of drinking water and food.
Germany pledged 200,000 million euros in aid through the World Food Program.
Medical teams have fanned out to prevent the spread of waterborne diseases.
The military-backed interim government is striving to cope and provided relief.
However, it blocked opposing political parties from assisting.
Army and government personnel have donated a day’s pay to the relief fund.
