Several days after its toy recall in August, Mattel identified the Chinese factory that had produced the toys as Lee Der Industrial.
Another U.S. toy company, Schylling Associates, recalled 24,000 Chinese-made tops because of lead paint.
The Chinese Government reacted by suspending exports by companies linked to the recall.
The Lee Der firm subsequently claimed it had been sold fake lead-free paint, and the head of the company committed suicide.
Leading toy retailer Toys R Us was looking for ways to expand its line of American-made toys, and the Toy Industry Association was seeking legislation requiring expanded toy safety inspections.
