On May 13, 2008, eight bombs went off nearly simultaneously in the Indian tourist city of Jaipur.
Casualty figures were at first unclear, but officials later said that 63 had been killed and over 200 injured.
There were no claims of responsibility.
The bombs were believed to have been planted on bicycles.
Police very quickly arrested two suspects and were seeking a third.
New Delhi and Mumbai were put on alert.
The bombings raised fears of renewed Hindu-Muslim violence, which has long plagued India.
The U.S., Britain, and France immediately condemned the bombings.
