Seven near-simultaneous bomb blasts at crowded market and religious sites killed 63 people and wounded 216 in Jaipur, India on 5/13/08.
Police described the bombing as terrorist attacks.
Foreign Islamic militant groups were suspected of stoking sectarian tensions and attempting to derail progress toward peace in Kashmir.
Two people were arrested and several others detained the following day.
Under high alert, security was tightened in New Delhi and other major cities.
Indian officials and foreign governments widely condemned the attacks.
