Soil erosion plagues much of China, turning arable land into uninhabitable desert.
Erosion, caused by over-farming, over-grazing, hillside farming, mining, deforestation, sinking water levels, and urban development, has outpaced government conservation efforts.
An estimated 61,600 square kilometers of land could disappear by 2010.
China’s government pledged to increase soil conservation efforts and imposed restrictions on urban growth and industrialization.
There are 11 major state-level water and soil conservancy projects in operation.
Twenty affected villages in Gansu Province will be vacated and replaced with newly-planted grass.
Conservation efforts include afforestation, terracing hillside farms and strict enforcement of conservation laws and regulations.
