Former U.S. football star O.J.
Simpson was arrested on robbery charges in Los Vegas on September 14, 2007.
The alledged victim, Alfred Beardsley, a sports memorabilia collector, claimed Simpson and some men entered his hotel room and two of them pulled guns during the robbery.
Simpson, who had been aquitted of charges in 1995 related to killing his wife and her friend, was later found liable for their deaths in a 1997 civil suit.
Simpson faces eleven charges, and his five accomplices ten each.
Simpson, currently behind bars in Las Vegas, stated he was only recovering articles stolen from him.
