A week of monsoon rains coupled with Himalayan snowmelt produced widespread flooding in Nepal, India, and Bangladesh in late July, 2007.
Bangladesh, which has a network of 230 rivers, was particularly hard hit, with floodwaters washing out roads, devastating crops, closing schools, and displacing or marooning some 5 million people.
By August 1, around 40 people were known to have died.
Waterborne diseases and lack of food and drinking water were becoming critical concerns for the displaced persons.
Thousands of soldiers, government workers, and volunteers were evacuating people and distributing needed supplies.
Flooding is an annual occurrence in low-lying Bangladesh.
