On October 23rd, two of Simpson's accomplices pleaded guilty to reduced charges and agreed to testify against Simpson and the others.
The judge agreed to delay the start of the trial in Las Vegas until September 8, 2008 in order to give the defendants time to prepare their cases.
Simpson was found guilty of all charges on October 4th, which included kidnapping and armed robbery, thirteen years to the day he was acquitted of murdering his ex-wife and friend.
He was sentenced to 15 years.
Simpson apologized to the court saying he didn't think it illegal to retrieve his property.
