Some popular toys made in China for US companies, including Thomas & Friends and TV character toys, are unsafe for children mostly because of paint containing lead.
Lead ingested by putting toys in mouths can cause brain and kidney damage and affect muscle and bone growth of children under 6.
Eighty percent of US toys are now made in China, where required safety procedures are not always followed.
Toymakers recalled the toys and fired the Chinese subcontractors.
The insufficiently resourced Consumer Product Safety Commission is investigating and talking with China.
Congressional bills propose strengthening the CPSC and ending manufacturers’ self-monitoring.
