Seven near-simultaneous bomb blasts hit crowded markets in Jaipur, India, beginning at 7:30pm Tuesday, on the 10th anniversary of India’s May 13 nuclear tests in Rajasthan.
An 8th bomb was defused.
Bombs were planted in bicycle wheels, several near Hindu temples, within a 50-foot radius.
They used RDX, ammonium nitrate, ball-bearings, and timing devices.
Dead were estimated at 45-80, both Hindus and Muslims.
Over 200 were injured.
Pakistani-backed Islamic terrorists were suspected, with a possible intent of stoking sectarian tensions, derailing the peace process, and damaging India’s economy.
No one claimed responsibility.
Police arrested two people and detained a dozen.
