Two co-defendants of OJ Simpson’s pleaded guilty to reduced charges and agreed to testify against him and the others.
Simpson was arrested in Florida for violating the terms of his release on bail.
A hearing was scheduled at the District Attorney’s request to consider revoking his bail.
On October 3, OJ Simpson was convicted on 12 charges, including armed robbery and kidnapping, for his role in the 2007 Las Vegas hotel-room incident.
He was sentenced to 15 years in prison.
Simpson’s lawyer vowed to appeal the convictions.
