China suspended exports from the two Guangdong-area factories that produced the recently-recalled RC2 and Mattel toys.
The head of Lee Der Industrial Co., Mattel’s manufacturer, committed suicide.
His best friend supplied his factory with the lead-tainted paint that prompted the recalls.
New recalls of Chinese-made toys include 24,000 by Schylling Associates for lead paint and 18 million by Mattel because they might release small, powerful magnets.
Many parents are now passing up Chinese-made toys.
Toys'R'Us Inc. is expanding its line of American-made and organic toys.
Toy makers adhere to voluntary standards, while big retailers do their own testing.
