In the country of Bangladesh, sandwiched between India and China off the Bay of Bengal, a major monsoon began its attack on Sunday, July 29, 2007.
Early unconfirmed reports said at least 10 people have died and 200,000 are marooned in the northern/northeastern part of the country.
People in India and Nepal are also being impacted.
By the following Wednesday, 4.5 million people living in 36 of the country's 64 districts were forced to flee their homes and the death-count was up to about 38.
Due to boat shortages, 500,000 are trapped with no access to food or clean water.
