In the wake of seven bombings in Jaipur on 5/13/08 the government imposed a curfew and dispatched anti-riot police.
A previously unknown group calling itself Indian Mujahedeen claimed responsibility for the attacks which reportedly were intended to disrupt tourism.
The group demanded that India stop working with the US and Britain.
Police determined that bombs were strapped to bicycles and released a sketch of a man suspected of buying the bicycles.
Casualty counts were adjusted downward to 61 dead and 90 wounded.
India’s Nationalist Party called a strike to protest the bombings and additional world governments expressed outrage and sympathy.
