Each of the 24 toys recalled for safety reasons in the US so far this year were made in China.
Recalled toys include a toy found to be filled with kerosene, an infant rattle that was a choking hazard and toy drums sets and bears recalled for lead paint.
Recently, RC2 Corp. recalled 1.5 million wooden Thomas & Friends trains and accessories, and Mattel recalled nearly 1 million of its Fisher-Price toy characters, all Chinese-manufactured toys found to contain excessive amounts of lead in their paint.
Lead paint is known to cause long-term neurological, learning and behavioral problems in children.
