China, with an estimated 40 percent of its territory suffering from soil erosion, is taking conservation measures all over the country.
The government is investing $2.46 billion dollars in northwest China to reverse desertification by planting trees, upgrading irrigation facilities, and setting up monitoring stations.
In China’s northeastern breadbasket, measures are being taken to stabilize the soil by planting trees, improving water retention facilities, and using natural fertilizers.
In the southwest, $2.1 billion has been allocated to protect important wetlands.
As a collateral benefit of soil conservation, officials anticipate augmenting energy supplies by cultivating bio-ethanol energy plants on reclaimed grasslands.
