Soil erosion in China is caused by overgrazing, deforestation, hillside farming, mining, urban sprawl, and global-warming abetted droughts.
Deserts now cover 1/3 of China’s land.
Desertification causes $7 billion in economic loss annually.
Since 2001 China has spent $9 billion planting trees, converting marginal farmland to forest and grasslands, and enforcing logging and grazing bans.
Government forces farmers and Tibetan herders to give up their way of life and relocate.
It restricts land lost to urban growth and industrialization, bans irrigation by well-water, and restricts hillside farming.
Eleven major conservancy projects reversed soil erosion over 10 percent of China’s land.
