In June, 2007, toy maker RC2 Corp. recalled 1.5 million Thomas & Friends toys that were decorated with lead paint, which can cause long-term neurological damage.
The recalled toys were made in China, as are at least 80 percent of all toys sold here.
RC2 fired the company that made the toys.
Subsequently, in August, Mattel recalled nearly a million children’s toys that also had lead paint.
Retailers pulled the items from their shelves, and Mattel expected to lose $30 million in income.
The two toy recalls raised concerns about the safety of Chinese-made products in general.
