Floods have been ravaging Bangladesh for over a week.
As of Wednesday, there have been at least 40 flood-related deaths.
Around 5 million people have been displaced or marooned.
Over 250,000 houses have been damaged or destroyed.
Over 500,000 acres of crops and 12,000 kilometers of roads have been damaged.
Major rivers fed by monsoon rains and snowmelt have inundated over half of the country’s 64 districts.
Thousands of soldiers, government employees and volunteer workers were deployed to evacuate people and distribute aid supplies.
The UK sent $2.5 million in immediate aid to provide food, water, shelter and medicine.
