Soil erosion is a critical problem for China, which has 7 percent of the world’s arable land but 20 percent of the world’s population.
Food production and the livelihood of millions of farmers are at stake.
Erosion is particularly severe in western China, where desertification has produced some $7 billion in annual economic costs.
Officials have made soil conservation measures a priority for several years and claim to have made significant progress in reversing soil erosion through government mandated conservation regulations, but erosion owing to overgrazing, water-table depletion, deforestation, and economic development has continued to outpace the government’s efforts.
