Soil erosion affects 40% of China’s territory, with 4.52 billion tons eroded annually.
Erosion has cost China at least 200 billion yuan in economic losses since 2000.
In the northwest, portions of Great Wall are eroding.
China’s breadbasket regions are in danger of losing fertility.
China is investing billions of yuan to reverse desertification.
Efforts include building forest belts around cities and oasis areas and upgrading irrigation facilities.
Experts are encouraging farmers to grow cover and compost crops on fallow land.
A major afforestation project has begun in the southwest.
So far, 20% of desertification-affected areas have been improved.
