Amadou Diallo was an unarmed immigrant from Guinea killed by 4 white police officers in New York City on February 4, 1999.
A grand jury indicted the officers who were arraigned on criminal charges of second degree murder.
The officers pled not guilty.
The trial date is January 3, 2000.
Each officer has separate legal counsel, but there is dissension among their attorneys.
The prosecutor is Robert Johnson, Bronx District Attorney.
Diallo's parents are represented by Johnnie Cochran who states they will file a civil suit as well.
The case has received extensive public and political attention.
