Despite cleanup efforts initiated in 2000, the Chesapeake Bay's oyster population has fallen sharply and reached a historic low.
Important bay water filters and indicators of the bay’s health, oysters were once the mainstay of the region's fishing industry.
Pollution, low oxygen and disease have caused their devastating decline.
Government regulators are now implementing an ecosystem-based management plan.
Managed reserves of seeded oyster beds have produced limited success.
Scientists are exploring the possibility of introducing disease-resistant nonnative Chinese oysters to the bay.
Bay conservationists have successfully reversed the loss of important water-filtering bulrush marshes by eradicating voracious nonnative nutria rodents.
