In the worst school killing in U.S. history, two students at Columbine High School in Littleton, Colorado, a Denver suburb, entered their school on Tuesday, April 20, 1999, to shoot and bomb.
At the end 15 were dead and dozens injured.
The dead included the two students, Eric Harris and Dylan Klebold, who killed themselves.
Harris and Klebold were enraged by what they considered taunts and insults from classmates and had planned the massacre for more than a year.
The school is a sealed crime scene and Columbine students will complete the school year at a nearby high school.
