Parkinson's is a degenerative brain disease.
There is no cure and the condition worsens with age.
Patients have tremors, difficulty pronouncing words, and rigid and slow movement.
The disease if characterized by the loss of cells producing the neurotransmitter dopamine, the protein alpha-synuclein, and clumping of proteins in the brain.
Sufferers include world leaders and celebrities and 1.5 million Americans.
Treatments increase dopamine.
Exercise may slow progression.
Many hope stem cell research--well funded in California--will find a cure.
Not generally inherited, the National Institute on Aging has associated two mutations in chromosome 12 in two disparate families.
