The giant panda is one of the world's most endangered species.
Called China's "National Treasure," they may date from the Mesozoic era.
Some 1600 live in the wild with less than 200 in captivity.
They are threatened by human civilization, starvation, and bad weather.
To save the panda, China is creating and expanding wildlife reserves and protection zones, planting forest areas with arrow bamboo, increasing financial support, rescuing sick or starving animals, and educating local inhabitants.
A panda blood bank is studying blood types and inbreeding is discouraged.
China wants the main habitat declared a World Heritage Area.
