A grand jury indicted four white New York City police officers for the February 4 fatal shooting of unarmed African immigrant, Amadou Diallo, struck by 19 of 41 rounds in the vestibule of his Bronx apartment building.
Edward McMellon, Sean Carroll, Kenneth Boss and Richard Murphy were each charged with two counts of second-degree murder and one count of reckless endangerment.
The four, who pleaded not guilty, face possibly 25 years to life in prison.
At their arraignment, bail was set at $100,000 each.
They will remain on restricted duty pending the outcome of the trial, set for January 3.
