A 64,000 square mile watershed, the Chesapeake Bay had been a rich source of seafood.
Maryland, Virginia, and Pennsylvania recognized that the Bay's environmental decline severely affected their economies and in 2000 agreed to actions to save the bay within 10 years, removing it from the national "impaired water" list.
However, five years later the Chesapeake Bay Foundation said bay quality had declined.
There were some successes.
The Oyster Recovery Partnership planted millions of disease free oyster seeds; law suits were filed to decrease nitrogen levels; and Ecosystem-based management was introduced to recognize the interdependence of ecological resources.
