"Bird Flu" (H5N1) a deadly influenza previously found only in birds, has killed four humans in Hong Kong.
Chickens may be the source; the means of transmission is unknown.
Human-human transmission is unlikely but possible.
Poultry farms were examined, but no evidence of H5N1 was found in the primary source of Hong Kong's chicken, Scenzhen.
To control the spread of the disease, the Hong Kong health department has advised residents to use proper hygiene, maintain body resistance through diet and exercise, purchase and handle meat with caution, avoid contact with birds, and report any fever or respiratory difficulties.
