Health authorities in Hong Kong reported a small but growing number of people infected with an H5N1 strain of influenza suspected to be transferred from birds to humans.
In a 1-month period, 10 suspected cases were reported and 9 confirmed, including 4 deaths.
Transmission modes remain unknown.
The World Health Organization and the Centers for Disease Control are investigating.
Nearby Macao reports no cases.
Impact on poultry farmers has been substantial with at least a 30% decline in sales.
Authorities are concerned of possible effects on the tourist industry.
Inspections of poultry farms have started.
