John and Patsy Ramsey are the only suspects in the murder of their daughter, JonBenet, found dead in their home on December 26, 1996.
The Boulder, Colorado, District Attorney questioned them in June 1998.
Two special prosecutors began to present the case to a 12-member grand jury on September 15.
The grand jury met only 18 times over the next 10 weeks.
Criticism abounded from claims of a rush to judgment to a pro-Ramsay bias.
Information was being leaked and both sides were using the press.
By January 9, 1999, the police were trying to identify a stuffed bear.
