In Boulder, Colorado, six-year-old JonBenet Ramsey was found murdered in the basement of her parents' home on December 26, 1996.
Intense media attention publicized leaks from police and attorneys, and public speculation.
A homicide investigator publicly resigned saying Ramseys were being set up.
In June 98 the case was handed over to the DA; in October a new police chief took office.
On September 15, the grand jury started work.
Following public criticism, the DA appointed 2 special prosecutors in September 1998.
No charges have been filed.
Public charges of bungling have been made against the police and the DA.
