On Sept 30, Merck voluntarily recalled the pain killer Vioxx, used by almost 2 million, after clinical trials for its use in colon cancer showed unacceptable rates of stroke/heart attack.
Results corroborated earlier warnings that had not resulted in recalls by the Food and Drug Administration (FDA).
As a COX inhibitor, Vioxx was safer for digestive tracts, important for arthritis patients.
Merck's advertising campaigns did not clearly warn about side effects.
The case highlighted concerns about drug manufacturers' advertising and FDAs role in insuring safety of drugs on the market.
Safety of other COX inhibitors is now a concern.
