A 23-feet tsunami struck the remote northwest coast of Papua New Guinea the night of Friday 17 July, totally destroying three villages and almost completely destroying another.
The death toll, mostly children and old people, has reached 59 but is expected to rise to more than 1000 and there are thousands of injured and homeless, with no food or water.
Australia is sending medical supplies and food and is expecting to set up a mobile hospital.
The tidal wave was caused by an undersea earthquake measuring about 7.0 on the Richter scale some 12 miles off the coast.
