A mysterious, deadly influenza strain, H5N1, has appeared in Hong Kong with nine confirmed and ten suspected cases.
Four people have died.
There have been no cases of this "bird flu" outside Hong Kong.
The source and means of transmission are unknown, although scientists believe it is through contact with chickens or their feces.
There is no evidence of human-to-human transmissions and no infected chickens have been found The Hong Kong government is coordinating interdepartmental efforts to prevent and control the spread of this "bird flu".
The World Health Organization has been asked to alert vaccine production centers.
