Life in the Chesapeake Bay is threatened by over-harvesting, pollution, parasites, and the introduction of non-native species.
The oyster population has been severely affected.
Fishermen, scientists, academics, and government are working together, establishing reserves with stricter harvesting guidelines and harvest-free sanctuaries.
A heartier species may be introduced, pending evaluation.
Federal regulators are testing 'ecosystem-based management' of resources in the Bay, primarily the striped bass and Atlantic menhaden.
However, results are depressing midway through a 10-year Bay clean-up program; bureaucracy and insufficient funding are blamed for hampering clean-up efforts, with suits being lodged against the EPA for dragging its heels.
