On September 30, Merck & Co. voluntarily withdrew its arthritis drug Vioxx, prescribed for some 20 million people worldwide, because recent scientific study results indicate that long-term use significantly increases patients' risk of heart attack and stroke over those taking older NSAID drugs.
Merck is facing numerous lawsuits alleging it made false and misleading statements about the drug's safety.
Documents show that, seven weeks before the withdrawal, FDA officials downplayed the significance of the recent findings and silenced one of its own experts who raised concerns.
Similar Cox-2 inhibitor drugs manufactured by other companies are now coming under scrutiny.
