Parkinson's disease is a degenerative nerve disorder in which certain proteins, such as alpha-synuclein, clump abnormally around brain cells.
Parkinson's involves the loss of cells that produce the neuro-transmitter dopamine, leading to tremors and stiffness and a deterioration of mobility and speech.
Although Parkinson's is not inherited, scientists studied two families with a history of the disease and they have isolated a gene whose mutations have been linked to the disease.
Treatment involves medications that increase dopamine levels, and exercise may help slow the disease.
Stem-cell research may lead to a cure for Parkinson's but it is a controversial issue.
