The worst school killing in US history occurred Tuesday 20 April at Columbine High School in a Denver suburb.
Two students, enraged at treatment by schoolmates, killed 12 students and one teacher and wounded dozens before killing themselves.
The entire nation mourned the massacre.
On Sunday Vice President Gore and the Colorado governor addressed an outdoor memorial service attended by 70,000.
The school was closed and turned into a crime scene, as police investigated whether others were involved.
Classes were scheduled to resume at a neighboring school, which the school's 1965 students would share for the remainder of the year.
