There are about 1590 Giant Pandas remaining in the wild, all in China.
Under state protection since 1962, they continue to be threatened by construction, mining, logging, poaching, and recent food shortages.
Priority is being given to increasing the forests and planting more bamboo.
The government set up over 50 reserves and organized teams to rescue and relocate weak or injured animals.
Exchange programs between habitats help maintain biodiversity.
Panda blood is studied to aid in breeding and to support panda rescue.
During the early 2000's the panda population has increased, and pandas have been observed returning to former habitats.
