In response to mounting demands from students and opposition groups, the wealth accumulated by Indonesia's former president Soeharto, his family, and his friends is under investigation.
On 13 November the Indonesian Assembly issued a decree on clean government that condemned corruption, collusion, and nepotism and specified that Soeharto’s wealth be investigated.
The Attorney General has set up two investigative teams and promised to search for assets overseas.
Soeharto has denied publicly that he amassed a fortune worth billions of US dollars during his 32-year rule.
Conflicting reports indicate that he has hired foreign lawyers or an unknown local lawyer.
