Obesity is a big problem in 1996.
Especially hard hit are Kuwait (about 50%), other Arab nations, southern China, and to a lesser extent Great Britain.
Obesity arises from bad diet, a sedentary life style, anxiety, many pregnancies, sleeping too much, and increases in income.
Obesity can lead to hypertension and other cardio vascular diseases, depression, kidney and liver diseases, and vein hardening.
Most dangerous is diabetes with complications of blindness, kidney failure, heart attacks, and amputations.
Prevention of obesity lies with improved diets at home and school, education on nutrition, and exercise.
Three Arab nations are successful with hypnotism.
