In Aruba, Natalee Holloway vanished early May 30, leaving behind luggage packed for her trip home.
The Kaploe brothers and Joran Andreas Petrus Van der Sloot, son of a judicial official, were questioned by police, released, but taken into custody June 9 under suspicion of murder/kidnapping but with no formal charges.
All three say they are innocent.
Attorney general Janssen and Police Supt. Straaten lead investigations and are taciturn.
The Holloway family, without police assistance, identified and located the three men in custody less than 24 hours after Natallee went missing.
They criticize the investigation.
Aruba residents criticize media attention.
