About 8 million people suffer from eating-related psychiatric disorders; 20% die from it.
Anorexics starve themselves, bulimics purge what they eat, purge-eaters purge but maintain weight, and binge-eaters just keep eating.
Causes include depression, stress from life events, and a need to control some aspect in one's life.
Anorexics and bulimics tend to be in denial.
They conceal their food-avoidance, which can lead to weakened hearts and osteoporosis.
Binge-eating disorder results in overweight, with accompanying life-threatening ailments like hypertension and cancer.
An epilepsy medication, topiramate, may help curb the urge to overeat.
Professional consultation and hospitalization programs may help.
