In early September, 1999, authorities worried about the growth of Hurricane Floyd as they tracked its movements from the Atlantic toward the U.S. coast.
Emergency management officials in Florida began mobilizing and the Governor declared a state of emergency.
On September 13, mandatory evacuations were ordered in Brevard County Florida, and coastal Georgia; hundreds of thousands fled their homes.
Experts speculated Floyd could become a catastrophic category 5 Hurricane, with winds over 156 miles per hour, the first such storm to hit the coast.
Individuals were urged to make homes as hurricane proof as possible.
