Dutch 17-year-old, Joran van der Sloot, is one of three suspects in the May 30 disappearance of American 18-year-old Natalee Holloway, on vacation in Aruba.
The three were with her the night she vanished.
Natalee's relatives flew immediately to Aruba.
They, not police, identified and located Joran.
Within 24 hours of her disappearance, they questioned him with police present.
He was not arrested until 10 days later.
Police searched the van der Sloot home and vehicles almost another week later.
His father, a judge-in-training in Aruba, was questioned on June 18.
Joran remains in custody for at least another week.
