Around 12:20 p.m. on August 14, Helios Airways Flight 522, bound for Athens from Larnaca, Cyprus, crashed near the Greek town of Grammatikos, killing all 121 onboard.
While the cause of the crash is unknown, terror attack has been ruled out.
The crew reported air conditioning system problems to Cypriot officials, but failed to make radio contact with Greek controllers.
Greek fighter pilots, scrambled to intercept the unresponsive Boeing 737, saw an unconscious pilot in the cockpit and oxygen masks dangling in the cabin, suggesting a catastrophic loss of air pressure.
Helios denied reports of previous technical problems with that aircraft.
