Mad cow disease (bovine spongiform encephalopathy) appeared in Britain in 1986.
It infected beef that had eaten feed containing animal brain and nervous tissue.
Mad cow spread through Europe and Asia, with isolated cases found in North America.
People who ate contaminated beef products, especially nervous system tissue, or received a contaminated blood transfusion contracted the human variant, Creutzfeldt-Jakob.
After at least 10 years victims experience personality change, loss of body functions, brain deterioration, and death.
By 2004, 151 people had contracted the disease.
Prevention includes killing herds, banning meat product in animal feed, testing older cattle, and halting imports,
