On April 24, six armed assailants abducted from the Malaysian resort island Sipadan 21 people, including Germans, French, South Africans, Finns, Lebanese, Philippine and Malaysians.
An American couple escaped.
The Philippine Muslim rebel group Abu Sayyaf, who demanded the release of Arab terrorists held in US prisons, claimed responsibility, although authorities were skeptical.
Malaysian and Philippine police and military were searching by air and sea.
An intelligence report claimed the hostages were taken by boat to the province of Sulu at the southern tip of the Philippines.
Five people were being questioned, including former employees of the resort.
