Tropical rain forests, such as those in China, Malaysia, Brazil, and several African nations, contain many rare species of flora and fauna.
Threats to these forests include encroachment by farms and industrialization.
Significant efforts are underway in China to enlarge and preserve these forests, including planting, prohibition or limitation on tree-cutting and factory building, relocation of farmers, and anti-poaching patrols.
Malaysia has a joint satellite project with Brazil to monitor rain forests and analyze the satellites' data.
Austria is providing Malaysian graduate students with scholarships in Rain Forest Management.
African lumber producers included rainforest onservation as a Timber Conference topic.
