Identity theft is the fastest growing crime in America with 350,000 people victimized yearly and $4 billion losses annually for businesses.
Stealing an identity requires only a social security number and one other personal information item (i.e.
mother’s maiden name) and takes victims years to recover.
Computerized information and mailed credit cards contribute to increased identity theft.
Solutions include shredding mail, guarding personal information, and checking credit reports annually.
The Federal Identity Theft and Assumption Deterrence Act of 1998 made identity theft a felony.
Victims are frustrated with a criminal justice establishment that puts a low priority on prosecuting fraud.
