Soeharto, former president of Indonesia, is being investigated by that nation's legislative body, the Indonesian Attorney General (AG) and his office, to determine whether his rumored wealth was gained illegally.
The investigation is in response to wide spread demands from students and opposition groups who contend Soeharto, his family, and friends gained wealth through corruption.
Estimates of Soeharto's wealth range from $20 to $40 billion.
The investigation expanded to include present and former government officials and wealth stashed abroad.
Soeharto obtained a lawyer who is a virtual unknown.
Soeharto swore publicly that he did not have any deposits abroad.
