Floyd became a hurricane on September 10, 1999.
It was north of Puerto Rico and the Virgin Islands.
By September 13, Floyd had become a Category 4, monster storm, expected to hit the east coast between Miami and Brunswick, Georgia, by September 15.
If the winds increase it would be only the third Category 5 storm to hit the U.S. FEMA has opened response centers, formed a liaison team, and pre-positioned supplies in Atlanta.
Florida has declared a state of emergency and is mobilizing.
Kennedy Space Center is being evacuated.
Citizens are urged to prepare and consider voluntary evacuations.
