Twenty people were taken hostage by six heavily armed assailants on a remote resort island in eastern Malaysia late Sunday 23 April.
They were taken in two boats headed for the Philippines.
The hostages consisted of ten foreign tourists - three Germans, two French, two South Africans, two Finns, and one Lebanese - 9 Malaysians including a policeman, and one Filipino.
Two Americans escaped.
The assailants, carrying AK-47s and a rocket launcher, claimed to be members of a small radical Muslim group fighting for an independent state in the Philippines.
Malaysian and Philippine police are both involved in the search.
