Helios Airways Flight 522 crashed near Athens shortly past noon on 14 August 2005, killing all 121 people aboard.
It is suspected a malfunction in the oxygen system caused a catastrophic loss of cabin pressure.
(There have been past reports of other oxygen-related problems on this airline).
However, experts are puzzled by the sudden incapacitation of first the crew and then the passengers.
Usually, warning systems on a plane this size provide for a safe descent, but this plane continued on automatic pilot until it suddenly lost altitude and crashed.
The Cypriot president announced three days of mourning.
