American Natalee Holloway, 18, disappeared in Aruba on May 30, 2005.
She was last seen with a Dutch citizen, Joran van der Sloot, and Surinamese brothers, Satish and Deepak Kaploe.
Police picked these men up on June 9 and arrested them on June 16.
The next day a tour boat disc jockey was also arrested.
Two security guards were also picked up but later released.
The investigation is being conducted by Aruba police, forensic investigators, and the district attorney.
Natalee's relatives had first identified the suspects.
The search for Natalee continued through June 19 and no charges have been issued.
