Identity theft is the fastest-growing crime, and one which evolves with each advance in technology.
Banks and businesses lose up to an estimated $4 billion annually.
Employee access to sensitive personal information increases the risk of identity theft.
Individual victims spend countless dollars and hours over the course of months or years in their efforts to restore their good names and credit.
The new Identity Theft and Assumption Deterrence Act of 1998 makes the crime a felony punishable by up to 15 years in prison.
On January 1, California became the ninth state to prosecute identity theft as a crime.
