Indonesian former President Soeharto's wealth, once estimated to be billions of U.S. dollars, is under investigation by Indonesian legislators.
In November 1998, following months of demands for an inquiry and statements from the government suggesting one was going on, the investigation became part of a general decree calling for the removal of all traces of corruption, collusion, and nepotism amongst current and former officials, their families and cronies, and businesspersons.
The government prosecutor's office is pursuing Soeharto's allegedly ill-gotten wealth, spread out around the country and overseas.
Soeharto has hired several non-government lawyers because he is a private citizen now.
