Obesity is on the increase in Asian countries with rates of over 10% - equal and greater than that of developed countries.
Causes are inactivity, poor diets, repeated pregnancies (Arab women), extra meals (Arab men), spoiling 'only' children (Chinese youth), fear, and anxiety.
Obesity rates can vary by age, gender, and education levels.
The percentage increases as living standards rise, although the incidence is lower in better-educated people.
Obesity leads to depression, diabetes, cardiovascular disease, and other life-shortening ailments.
Health Departments around the world are advocating sensible diets and exercise.
Hypnotherapy is being used successfully on obesity in several countries.
