Creutzfeldt-Jacob disease, the brain-wasting human form of mad cow disease (MCD) believed to come from eating beef infected with the disease or from blood transfusions, has killed more than 150 people worldwide since discovered in Britain in 1996.
Most cases have occurred in Britain, plus eight in France and two in Ireland.
In an effort to control the spread of the disease, many countries have placed a ban on the import of beef, imposed tougher screening and slaughtering controls, and destroyed whole herds of cattle.
These measures have devastated the European, Canadian, and U.S. cattle industries.
