Mad cow disease, or bovine spongiform-encephalopathy (BSE), started in Britain in 1986.
It devastated beef industries; in Canada $5 billion was lost in 2003-2004.
Fear of BSE produced embargoes; 3 dozen nations halted U.S. beef imports in 2003.
Humans who have eaten infected beef can contract variant Creutzfeldt-Jaacob Disease (vCJD) which is fatal.
It has an incubation period of 10 years or more; today's patient could have eaten infected beef 10 years ago.
Positive diagnosis is confirmed only by autopsy.
In Britain, 147 are known dead of vCJD, another 10 elsewhere.
Prevention is through testing and changes in cattle feed.
