On September 11, tropical storm Floyd became the fourth Atlantic hurricane of the year, moving through the North Atlantic toward the eastern US.
Moving away from the Caribbean's Leeward Islands toward Florida, Category 4 Hurricane Floyd, with 131 mph winds that reached 155 mph around the eye, extended 700 miles in all directions.
In Florida, emergency management officials mobilized and the governor declared a state of emergency.
Mandatory evacuations were ordered in Florida and Georgia, and cruise ships and pleasure craft left for safer waters.
FEMA emergency response centers positioned ice, water, cots, tents and emergency food and medical supplies.
