Eating disorders are a mental illness, difficult to treat since patients are in self-denial, with high morbidity and mortality (20% die).
They include anorexia (self-starving), bulimia (purging), binge-eating disorder, and variations.
Between 1.5 to 11 million American women have or will have anexoria; more have bulimia.
Historically affecting younger females and fewer males, trend data show changes.
Permanent effects include weakened hearts, severe osteoporosis, brittle teeth and bones, and loss of stamina.
Effective treatment is long term, usually not insured (due to lack of specific diagnosis criteria), and includes psychiatric counseling and gentle persuasion by friends and family.
