In February 1999, Austria suffered its worst avalanches in 45 years because of almost unparalleled amounts of snow and high winds whipping it into drifts and making it unstable on the crust of earlier snow.
In the ski resort of Galtuer near the Swiss border, 16 were confirmed killed and 20-30 were missing from two avalanches on consecutive days.
The first avalanche was 15-20 feet high and 300-500 feet wide; the second was 45 feet high.
In other avalanches, in nearby Ischgl, one woman was killed and six others were missing, and in Valzur two were killed.
