The so-called Unabomber, 54-year-old former mathematics professor Theodore Kaczynski, accused of killing three and injuring 23 during a campaign against technology between 1978 and 1995, is awaiting trial in Sacramento, California.
Jury selection is scheduled to begin November 12, 1997, and the trial is expected to last six months.
In April 1996, Kaczynski was arrested by the FBI at his remote cabin in Montana after being turned in by his brother David.
Authorities had been searching unsuccessfully for him for 18 years.
Kaczynski intends to plead innocent at trial, and prosecutors are unsure if they will seek the death penalty.
