On November 22, middle school teacher Debra LaFave pleaded guilty to lewd acts with her 14-year-old student, in exchange for three years house arrest and seven years probation, thereby avoiding possibly 30 years in prison.
The victim's family agreed to the deal to save their son from a media frenzy at trial, where LaFave would plead not guilty by reason of insanity.
Her lawyer rejected an earlier offer of three years in prison, arguing that she was too beautiful to survive in prison.
However, a hitch developed when a judge balked, wanting more information and changes to the plea.
