In Sacramento, Theodore Kaczynski faces a 10-count federal indictment for 4 of the 16 mail bomb attacks attributed to the Unabomber in which two people were killed.
If found guilty, he faces a death penalty.
Kaaczynski also faces New Jersey charges for another fatal bombing.
He has pleaded innocent to all charges.
U.S. District Judge Garland Burrell Jr. presides in Sacramento.
The trial may take 6 months.
Attorneys made opening statements in January 1998.
In New Jersey, Judge Debevoisse heard defense arguments for combining all charges at a single Sacramento trial.
Kaczynski's defense attorneys are Quin Denvir and Judy Clarke.
