The US Fish and Wildlife Service may remove Yellowstone grizzly bears from the endangered species list.
The population has made a significant recovery, tripling since 1983, but the grizzlies reproduce very slowly and some of their food sources are threatened.
This would open privately owned lands in the area, about one-third of the current habitat, to logging, recreation, and development.
The responsibility for managing the bears would be turned over to three nearby states, Wyoming, Montana, and Idaho.
The National Wildlife Foundation supports the move; the Sierra Club, Natural Resources Defense Council, and other powerful environmental organizations oppose it.
