Theodore Kaczynski is suspected of being the Unabomber, the mail-bomb terrorist who killed three and injured 23 others in 16 bombings over an 18-year period.
Kaczynski is charged with four of the Unabomber's 16 attacks, including two fatalities in California.
He is also charged with a fatal bombing in New Jersey.
He has pled innocent in the first trial, which will be held in Sacremento and address the California deaths.
Prosecutors say they have a lot of evidence, including Kaczynski's incriminating diaries, which defense lawyers Quin Denvir and Judy Clarke tried unsuccessfully to have excluded from the trial.
