Russell Henderson and Aaron McKinney, both 21, are charged with murder for the October 6, 1998 beating death of university student Matthew Shepard in Laramie, Wyoming.
Both face the death penalty if convicted.
Jury selection for Henderson's trial, rescheduled from March 22 to April 6, began March 24.
The defense will argue that Henderson was more a witness, rather than perpetrator of the crime, attempting to shift the blame to his co-defendant.
Police say the crime was motivated in part because Shepard was gay.
The brutal killing prompted gay rights activists and Shepard's mother to lobby for stronger hate-crime laws.
