Thursday 20 August the U.S. bombed a factory in Khartoum, wreaking heavy damage and injuring 10 people, 4 of them critically.
More casualties may lie under the rubble.
The U.S. said the attack was in retaliation for the bombings of U.S. embassies in Kenya and Tanzania three days earlier and claimed that the factory was producing chemical weapon agents and was linked to Osama bin Laden.
Sudan maintained that it was a pharmaceutical factory and asserted that the attack was intended to divert attention from the Monica Lewinsky scandal.
Khartoum staged anti-U.S.
demonstrations Friday.
