Japan plans to seek permission to expand its so-called research whaling program when the International Whaling Commission (IWC) meets in late May, intending to nearly double its annual catch of minke whales and to hunt endangered humpback and fin whales.
Australia, New Zealand, and conservationists strongly oppose Japan's plan to expand whaling in the Australia-declared whale sanctuary in Antarctic waters, but they have no legal recourse to stop it.
Australia's prime minister appealed directly to his Japanese counterpart, urging him to reconsider his position.
He dispatched lobbying missions to Europe and the Pacific to rally IWC votes against Japan's plans.
