Russell Henderson and Aaron McKinney are charged with 1st-degree murder in the death of Matthew Shepard, near Laramie, in October 1998.
They are also accused of kidnapping, beating, and robbing Shepard, before leaving him tied outdoors in freezing weather.
(He died in hospital).
Henderson's trial comes first, the prosecutor being Cal Rerucha.
The defense lawyer claims Henderson was merely a witness to McKinney's crimes.
He also said the crime was not pre-meditated.
Authorities state the motivation was partly because Shepard was gay, and they had posed as homosexuals to lure him.
If convicted, both men could face the death penalty.
