Avalanches on 23 and 24 February 1999 struck an Austrian ski region, including villages of Galtuer, Valzur, Gargellen, and Ischgl.
At least 25 people were killed with dozens missing.
Houses and cars were crushed by snow walls as large as 45' deep and 600' wide.
Thousands of tourists were stranded.
At first snow and wind limited all but local rescue attempts.
By the second day 200 army troops were helping, and a dozen helicopters transported injured to a hospital in Landeck, where rescue headquarters was located.
These avalanches were set off by the fiercest Alpine snowstorms in 50 years.
