According to the FDA, between 1988 and 1998 there was a fivefold increase in food products recalled for E.coli and Listeria bacteria and other life-threatening contaminants.
Listeria was suspected or found in meat products of several companies, and one company's hot dogs were blamed for sickening 70 and killing 16.
In a normal year Listeria is estimated to cause 1,850 illnesses resulting in 425 deaths.
The Agriculture Department urged consumers to return all recalled products and to properly handle, cook, and store food.
It was considering requirements for more industry testing.
The President proposed giving increased authority to food agencies.
