The worst snow storm in 50 years and high winds are causing avalanches in Austria.
The Galtuer ski resort area was hit by avalanches on February 23 and 24, 1999.
Ten houses were crushed, 16 people dead, 17 injured, and 15 missing.
Initial rescue operations were by locals then Austrian troops and helicopters were brought in.
The United States, Germany and Switzerland offered additional helicopters.
An emergency command post was established to take victims and send food and supplies.
Also on February 24, an avalanche struck Valzur, killing two.
On February 22, an avalanche buried two, one dying, in Gargallen.
