There has been a sudden increase in U.S. food recalls because of centralized food processing and wide distribution.
Tainted foods present a major health threat to the elderly, pregnant women, the very young, and those with weakened immune systems.
The bacteria are found in hot dogs, cold cuts, and soft cheeses.
In response to an outbreak of food poisoning, the government and/or company can recall the products and stop production operations, but the consumer must check product codes, cook meats to 165 degrees, separate raw foods and uncooked meats, and wash hands and cutting tools thoroughly.
