Australia and New Zealand are strongly opposed to Japan's plans to seek approval at the International Whaling Commission (IWC) to enlarge its catch of whales in Antarctica.
Japan wants to almost double its catch of Minke whales and add humpback and fin whales, both of which are endangered.
There is a moratorium on commercial whaling, but Japan hunts them under a loophole that allows "research whaling".
It does not recognize Australia's claim of sovereignty over Australian Antarctic Territory.
Whaling opponents fear that pro-whaling countries like Japan and Norway could get a majority vote at the IWC.
