In 2005, after 30 years on the endangered species list, the US Fish and Wildlife Service was preparing to delist Yellowstone's grizzly bear contingent, whose numbers have increased from about 200 to 600.
However, protection would continue in 6,000 square miles of the bears' core habitat in the park and adjacent federal lands and they would continue to be monitored by federal scientists.
Responsibility for managing the grizzlies outside of Yellowstone and Grand Teton Parks would be turned over to Montana, Idaho, and Wyoming officials, who could allow limited hunting.
Environmental groups disagreed over whether the bears remained at risk.
