The Yellowstone grizzly bear, a revered symbol of the American West, has been threatened by competition for food, low birthrates, and hunting as well as loss of habitat from industry, recreation, and development.
A population under 500 can lose genetic diversity and be vulnerable to disease and birth defects.
Besides putting them on the Endangered Species List in 1975, measures to protect them included hunting bans, road closures and fences, relocation, and garbage removal.
This brought the Grizzly to a population of over 600 and possible removal from the List.
Conservation groups are divided over the latter possibility.
