Former Hillsborough County teacher Deborah Lafave pled guilty to two counts of lewd and lascivious battery in exchange for three years of house arrest and seven years' probation.
Accused of having sex with a 14-year-old boy, she would have faced up to 30 years in prison if convicted.
Their son's emotional health was cited by the youth's parents when they agreed to Lafave's plea deal instead of a trial.
However, the judge in neighboring Marion county, where one of the encounters took place, wants more information on a trial's impact on the two youth involved, thus reopening the investigation.
