Matthew Shepard, a gay college student in Laramie, Wyoming, was kidnapped, pistol whipped, robbed, and left for dead in October 1998.
He died 5 days later.
Russel Henderson and Aaron McKinney are charged with 1st degree murder, kidnapping, and aggravated theft and face the death penalty.
McKinney's trial is set for August 9.
The jury selection for the Henderson trial began on March 24, with opening arguments to begin April 6 with a five-week trial.
The judge is Jeffrey Donnell, prosecutor Cal Rerucha, and defense attorney Wyatt Skaggs.
Twenty-nine of 71 potential jurors were dismissed during the first two days.
