For 18 months, media fed the public details about attractive Debra LaFave, former Tampa Florida middle school teacher, and her student lover, a 14-year old boy.
Her guilt of lewd conduct with a minor in Hillsborough county was admitted before trial.
At issue was sentencing.
November 21, prosecutor and defense agreed on a plea deal allowing her to avoid prison.
The prosecutor said media attention made the boy's family want to end the process.
Defense attorney said media coverage was the most critical factor of the entire case.
Objections by a Marion County judge may change the plea deal.
