In central Europe, the worst snowfall in 50 years triggered February avalanches that hit ski resorts and towns in Austria's western states of Triol and Vorarlberg, blocking roads and stranding tens of thousands.
The Galtuer resort, near the Swiss border, was hit by two consecutive avalanches on February 22 and 23, and early reports said at least 16 were dead, 30 injured and 29 missing.
Avalanche deaths and injuries were also reported in Valzur and Ischgl.
Austria established a center in Landeck for sending supplies and receiving victims by helicopter.
Avalanches have killed 60 this year throughout Europe.
