From October 1998 to February, food produced in the United States was tainted with Listeria, E. coli, enterotoxigenic E. coli, and lead, causing recalls of products.
Listeria caused nine recalls of meat with one producer causing 82 illnesses and 12 adult deaths.
One recall for E. coli and one recall of baby food containing lead resulted in no illnesses.
In July 1998 President Clinton asked for more money and authority for the Food and Drug Administration, to facilitate faster recalls, warning labels, and a food safety research institute.
Rigid food safety practices are the best way to avoid infection.
