The use of safety helmets is being promoted to prevent head injuries amongst motor- and bicyclists, as well as players in team and individual sports.
Helmets can reduce fatalities and serious brain injuries, and may prevent concussions, although in some cases there is insufficient evidence.
Countermeasures include cyclists' helmets' being mandatory in Argentina and Uganda, strongly advised in the ASEAN nations, and recommended for Australian cowboys and mounted sheepherders.
New York is the 7th state to require helmets for skateboarders; cyclists and inline skaters already covered by law.
Many schools and clubs are now using special headgear for soccer players.
