On 20 August 1998 U.S. missiles hit a Khartoum factory, avenging the 7 August bombings of U.S. embassies in Nairobi and Dar-es-Salaam which killed over 250.
The Clinton administration claimed the building produced chemical weapons agents; Sudan asserted it was a pharmaceutical factory.
Casualties include 10 injured and several missing.
Clinton accused Sudan of supporting Osama bin Laden's terrorist activities, including bombing the embassies and hosting terrorist camps as well as financing the factory.
(Simultaneous U.S. strikes hit bin Laden camps in Afghanistan).
Sudan asked the U.N. for an investigation, as anti-U.S.
demonstrations erupted all over the Middle East.
