Rebellion has increased dramatically in Baluchistan, where tribesmen demand greater royalties from gas reserves and object to the army's establishing new garrisons.
Rebels attacked a paramilitary convoy and a base near Dera Bugti on 17 March, killing up to 30 people and injuring more than 70.
Two trains were bombed killing 2 and injuring 8, a bomb killed 39 at the memorial of a Muslim Sufi saint, and 17 minority Hindus were killed when their temple was hit by rockets Thousands of government employees and their families, and thousands of women and children of local tribesmen, fled their homes.
