The rapidly declining number of frogs and other amphibians indicates environmental degradation that may affect all of us.
Amphibians' permeable skins and habitats make them an important indicator of environmental quality.
One study found that 32% face extinction.
Reasons for this include habitat decline (water pollution, pesticides), over-harvesting for food and medicine, and increasing number of lethal and previously unrecognized frog diseases.
Corrective actions include reducing emissions that contribute to climate change, creating parks and ecological reserves, and breeding frogs in captivity in order to sustain vulnerable species.
