Chesapeake Bay oysters have almost vanished because of pollution, over harvesting, and two parasites.
They are critical to the health of the bay because they filter the water Virginia and Maryland have been spending several million dollars every year to restore native populations, and more than 330 million oysters have been planted since 2000.
Virginia and Maryland are considering introducing an Asian oyster but others want more studies done on potential impact, since they could bring new diseases and problems and could squeeze out the native oysters altogether.
Moreover it would be impossible to remove them once they were introduced.
