Victor Yushchenko, Ukrainian candidate for president, became ill on September 6, 2004, after dining with security service officials.
Yushchenko suffered severe pain, internal bleeding, and facial disfigurement.
He entered an Austrian clinic where doctors suspected poison.
Yushchenko accused "government officials." Yushchenko won a November run-off election, but results were negated and a December run-off was scheduled.
On December 10 Austrians confirmed he was poisoned with dioxin.
A criminal investigation was reopened with strong US urging.
This attack apparently was to prevent his election victory.
He had promised to investigate past assassinations and the administration accused him of US financial backing.
