Ephedra, also called ma huang, is an herbal stimulant containing the chemical ephedrine.
It is an ingredient in a variety of weight-loss, energy-boosting, and body building supplements.
It can be dangerous to people with certain underlying health problems.
Side effects include anxiety, insomnia, hypertension, tachycardia, psychosis, kidney damage, dependency, heart attack, and stroke.
It is linked to over 12 deaths worldwide.
Ephedra can produce an amphetamine-like rush, and is used to make methamphetamine.
Having received hundreds of complaints about ephedra, the FDA has issued warnings and is considering establishing limits on its use.
Several states have banned ephedrine-containing supplements.
