A Level 3 (the highest) volcano alert is issued for Mount St. Helens, Washington.
In late October 2004 there were seismic rumblings.
On November 1 a 24-minute 1,000-foot plume appeared.
After more earthquakes, on November 2 there was a brief shot of steam and a 50-minute low-frequency tremor.
On November 3, a second tremor lasted 25 minutes.
Mount St. Helens erupted in 1980 killing 57.
Tourists gathered.
An observatory 5 miles away was evacuated, but towns have not been evacuated.
Scientists are monitoring the volcano with aircraft (sampling the air and detecting hot spots), seismographs, and global positioning sensors.
