A November 2004 natural gas leak on Norwegian Statoil's Snorre A oil platform in the North Sea caused the shutdown of production from Snorre A and neighboring platform Vigdis, resulting in a cut in oil output of 205,000 barrels a day for Norway and costing Statoil 1.4 million Euros daily.
The leak, which could have caused a catastrophic explosion, was contained 18 hours after it was reported.
There was no evidence of oil leaked into the water, and there were no injuries.
Statoil's request to restart operations would not be granted until an inspection by the Norwegian Petroleum Safety Authority.
