The South Korean president initiated an investigation of illegal wire-tapping by NIS (the intelligence service).
This produced 274 illegal recordings, and led to the arrests of a retired NIS official, who had kept an illegal tape, and the businessman to whom he gave it, who then leaked it to the media.
It resulted in the resignation of the ambassador to the U.S., heard on the tape in an incriminating conversation with a Samsung executive, discussing allegedly illegal political contributions.
Samsung apologized and filed a libel suit.
NIS' current chief admitted his agency's earlier bugging operations.
The media are being questioned.
