On November 28, escaping natural gas posed risk of explosion on an oil-drilling platform in the North Sea.
Most workers were evacuated and oil production halted.
Operated by Statoil, Norway's state-controlled oil company, this platform also processes oil from nearby Vigdis field.
Statoil thought production could resume in a month but Norway's Petroleum Safety Authority has approval authority and said that damage may be greater than first believed.
A month-and-a-half after the closing, Statoil asked to partially resume production though it would take time to reach even limited production goals.
Statoil is losing $1.8 million daily.
