Agent Orange is a defoliant used during the Vietnam War to strip away the protective cover used by North Vietnamese troops.
It has a lingering toxic component called dioxin, which has been linked to three kinds of cancer and chemical acne among the Vietnamese and in Americans fighting there, as well as birth defects in their children.
However, it is virtually impossible to determine which ailments came directly from Agent Orange.
Research continues and U.S. law requires review every two years.
Dioxin caused widespread environmental damage In Vietnam; precautions are taken as suspected caches of dioxin are still being found.
