The Veterans Administration recognizes 10 diseases and the birth defect spina bifida as linked or possibly linked to Agent Orange.
Any American who served in the war is automatically presumed to have been exposed to the defoliant.
Agent Orange was sprayed on jungles by US planes for 10 years to strip away cover from North Vietnamese troops.
Vietnam estimates that up to 2 million of its citizens suffer from Agent Orange-associated ailments, but its studies are discounted by Western experts for lack of stringent methodology.
Vietnam has launched a support fund, managed by the Red Cross, for Agent Orange victims.
