Ephedra, a diet supplement and herb containing ephedrine, is a heart stimulant that may cause physical and mental problems, and death.
Producers claim it increases energy, helps take off weight, tones muscles, and increases sexual sensation.
Millions of people, especially athletes, are taking this supplement.
Its unsupervised sale was made possible by 1994 legislation which removed Food and Drug Administration (FDA) oversight of diet products.
The deaths of 40 and incidents involving 800 have caused the FDA to try to limit supplements to 8 mgs per dose, 24 mgs per day.
Chinese and Texas authorities are also concerned.
