Theo van Gogh, 47, died in Amsterdam, the Netherlands, on November 2, 2004.
The Dutch filmmaker and distant relative of Vincent van Gogh was shot and stabbed by a 26 year old Dutch/Moroccan Muslim.
The police immediately arrested the assassin, although both he and one of the police were shot.
Van Gogh was vocally anti-Muslim and had been receiving death threats.
Fear of further polarization and intolerance in the Dutch society spread.
Twenty-thousand attended a memorial service and Dutch and Muslin leaders expressed concern, calling for calm and dialogue.
Police interviewed witnesses, searched apartments, took evidence and arrested eight Muslims.
