In late July South Korean TV and newspapers released illegally taped private conversations between a major newspaper publisher and a Samsung executive, in which they discussed Samsung's providing a $3 million slush fund for candidates in the 1997 elections.
NIS apologized for illegal wiretapping, which continued until March 2002.
Samsung apologized for the scandal.
The newspaper publisher, Hong, appointed ambassador to the US in February, resigned.
A former intelligence official was arrested after trying to commit suicide.
He had given the recordings to a Korean-American businessman who leaked copies to the media after failing to blackmail Samsung.
