Mangroves grow in thickets along tropical coastlines with tangled roots above ground and salt-filtering taproots.
Acting as shock absorbers, they are vital in protecting the shore.
They teem with life, providing a safe haven for fish, birds, crustaceans, and shellfish.
Up to half of the world's mangroves have disappeared in the last 20-30 years because of the development of tourist resorts and commercial prawn farming.
There are now fewer than 40,000 acres left.
The UN has called for the rehabilitation of mangroves damaged by the recent tsunami, noting that there was much less damage in mangrove-protected areas.
