Frogs are disappearing at an alarming rate across the globe.
Frogs are very important indicators of environmental change because their permeable skin is extremely sensitive to any changes.
They are threatened mainly by climate change and fungal disease, but also by pollution, deforestation, habitat loss, and harvesting for food and medicines.
There was also a dramatic increase in the number of hermaphrodites among frogs during the period when DDT and other pesticides were widely used.
To reverse this trend, we must protect their habitat in part by creating parks and reserves, reduce emissions, and breed them in captivity.
