The Asian herb Ephedra contains stimulants known chemically as ephedrine.
Pure ephedrine can be used to make methamphedamine, a highly addictive street drug, but in controlled dosages it is prescribed for colds and asthma.
As an herbal dietary supplement, outside FDA control, it can decrease appetite, improve concentration, raise metabolism, and enhance sexual performance.
But it can be habit-forming; reports of deaths and other negative side effects (including anxiety, insomnia, hypertension, psychosis, kidney damage, heart attack, and stroke) have led to the rare case where the government takes action against an herbal product, considering regulations on sales, labeling, and dosage.
