The Chesapeake Bay's Maryland oyster has been decimated by over-fishing, pollution and parasites.
Oyster harvests dropped 92% in five years.
As a revenue source, oysters declined from $65 million annually to $500,000.
There are efforts to save or replace the oyster.
At managed reserves, Maryland plants disease free oysters, gives them 3 years to grow, then allows harvesting.
Research continues on the asian oyster, successfully grown in Seattle waters, to see if they will be disease resistant and not harm the bay's ecosystem.
Virginia and Maryland Governors will decide whether more research is needed when study findings are presented.
