Dutch filmmaker Theo van Gogh, known for his controversial views, was murdered on an Amsterdam street on 2 November 2004, in broad daylight.
The assailant, of dual Dutch/Moroccan nationality, was captured and arrested after a shootout in which he and a policeman were wounded.
The motive is believed to be radical Islamic views; the filmmaker had received numerous death threats following the airing of an anti-Muslim movie.
Whilst admitting Van Gogh's views were hurtful, Muslim groups condemned the killing and called for calm.
Meanwhile, thousands gathered for a raucous memorial rally.
Police later arrested eight associates of the assailant.
