On November 28, 2004 Norway's Statoil closed the SnorrA and Vigdis oil platforms in the North Sea.
A gas leak caused the SnorrA to become unstable and it could explode.
The leak was contained then Statoil began pumping drilling mud into the injection well.
This closure dropped Norway's production by 205,000 barrels per day, costing Statoil $1.8 million a day.
Statoil hoped to resume operations by December 31, but bad weather and safety authority approval delayed plans.
Statoil requested approval on January 13.
Another North Sea leak caused Marathon Oil Corp to close the Brae Alpha platform on November 30.
