November 2, Dutch filmmaker Theo van Gogh was murdered on an Amsterdam street.
His film "Submission," about the treatment of women in Islamic society, outraged the Muslim community.
A note left on the body called for holy war.
Police quickly apprehended the suspect, a Muslim of dual Dutch and Moroccan citizenship.
Eight suspects were arrested in connection with the murder.
Dutch Muslim groups in Amsterdam condemned the killing and pleaded for dialog.
Some 20,000 people gathered in a noisy tribute to van Gogh, while opinion polls showed many Dutch feel threatened by the nearly one million Muslims in the Netherlands.
