Oysters are disappearing from the Chesapeake Bay.
Once bringing $65 million into Maryland annually, they now bring but $500,000.
They also brought tourists and, most importantly, filtered the water of the bay.
Their decline is attributed to over-harvesting, pollution, and two parasites appearing in the 1960's, one brought by Asian oysters.
Maryland, Virginia, and the national government are spending millions to save the oyster.
Research centers harvest seed and maintain managed reserves.
Sewer system discharge and farm run-off must be controlled.
Some want to introduce a new Chinese specie to the bay, but others fear the consequences of this move.
