In early December, Austria's Rudolfinerhaus clinic announced that tests confirmed that orally administered dioxin had poisoned Viktor Yushchenko.
He was admitted to the clinic twice in recent months in serious condition.
Yushchenko is in a contested election for president of the Ukraine, running against the current prime minister.
A runoff election will be held December 26.
After dioxin poisoning was confirmed, the Ukraine prosecutor general reinstituted a criminal investigation.
Yushchenko believes the poisoning was political reprisal and the aim was to kill him.
The U.S. has denied charges that it financially supports Yushchenko whose political rival is pro-Russian.
