The U.S. sprayed 19 million gallons of the defoliant Agent Orange (containing dioxin) over South Vietnam from 1962 to 1971, exposing two million Vietnamese and 2.1 million U.S. military.
Vietnamese veterans and civilians have various ailments and their children suffer from physical deformities and mental retardation.
The sickest are tended in special villages.
In 1999 Vietnam began a survey to find the exact number of sufferers, but 70,000 are known The U.S. Veterans Affairs Department acknowledges Agent Orange can cause three cancers, chloracne, spinal bifida in offspring, and seven other diseases.
They have received 92,000 claims and treated 50,000 cases.
