Britain's Food Standards Agency (FSA) recalled 474 food products found to contain the carcinogenic Sudan I red dye.
Used to color solvents, waxes, petrol and shoe polish, it is illegal for use in food.
However, the risk of illness is estimated to be very small based on the concentrations used.
The food safety alert was issued February 18 after Italian authorities discovered the dye in a batch of Worcestershire sauce from England.
The recall affects 12 EU states and China.
The FSA investigation into how the dye found its way into the British food chain is focused on three companies.
