Red dye Sudan I, approved for non-food use, was found in Worchester Sauce in 2005.
Britain issued a safety alert on February 18 and began withdrawing products containing this sauce.
Eventually 474 products were identified.
Residents, restaurants, and retailers were notified.
The dye was banned by Britain and the European Union in 2003, but was discover in Indian-produced chili powder put in the sauce and probably imported earlier.
This dye increases the risk of cancer, although that increase is very small.
Products had been exported to European countries, North America, the Caribbean, and China.
Britain has begun an investigation.
