After 2 months of testimony, attorneys presented closing statements in the murder trial of Robert Blake, actor, which now goes to the jury.
Accused of murdering his wife of less than a year, Blake pleaded innocent.
Prosecuting attorney Samuels emphasized Blakes' dislike of his wife, his desire for a divorce, and allegations he'd tried a murder-for-hire scheme.
Defense attorney Schwartzbach cast doubt on the veracity of witnesses in that scheme and emphasized lack of physical evidence.
If convicted, Blake faces a life sentence plus 9 years if found guilty on the attempted murder-for-hire.
Blake did not testify.
