Former Lebanese Prime Minister Rafik Hariri was killed by a suicide car bomb February 14, 2005 in Beirut.
Six of his body guards and 10 other were also killed with about 120 injured.
Two Islamic terrorist groups claimed responsibility but opposition leaders blamed the Lebanese and Syrian governments.
Hariri opposed Syrian intervention in the Lebanese presidential term and was working to make a comeback in the May election.
The opposition, France, and the US called for the withdrawal of the Syrian troops.
The opposition and France called for an international commission, while the opposition also demanded the Prime Minister's resignation.
