Pfc. Lynndie England pleaded guilty to humiliating and assaulting prisoners at Abu Ghraib prison near Baghad late in 2003.
In hearings, England said her actions were wrong but early in the trial she contradicted that statement.
Judge Col. Pohl stopped her and said he didn't want her to plead guilty unless she thought she was.
Military judges cannot accept a guilty plea if the defendant doesn't accept guilt.
If accepted, a military jury decides punishment and defendant gets the lesser of that or the plea agreed to by prosecutors.
Defense attornies are Capt. Crisps and Rick Hernandez.
