A massive tsunami hit coastal communities from southern Asia to Africa on 26 December, killing at least 150,000 people in 11 countries.
It was caused by the biggest earthquake in 40 years, 8.7 on the Richter scale, off Indonesia's Sumatra Island.
Indonesia was the hardest hit, with at least 90,000 dead.
and its Aceh province was devastated with at least 500,00 homeless.
Sri Lanka and the Maldives also suffered tremendous losses and damage.
International aid has been sent from a host of countries, including the US, Japan, Australia, Bangladesh, Uzbekistan, Denmark, and Switzerland.
