An 8.7 degree earthquake off Sumatra Island, followed by a killer tsunami, devastated parts of Asia on 26 December 2004, killing nearly 150,000 in 11 nations.
This was the world's largest earthquake in 40 years.
Foreign militaries led by the United States are assisting with relief efforts.
China sent a quake-rescue team to Indonesia, where nearly 500,000 were rendered homeless.
Australia and Japan contributed millions of dollars and Japan committed to help with reconstruction.
Supplies were sent by China, Bangladesh, Uzbekistan, Denmark, and Switzerland.
Indonesia plans to host 23 nations in a summit to discuss the aftermath of the disaster.
