Former Lebanese Prime Minister Rafik Hariri, and at least 14 others, was killed in a poweful explosion in central Beirut, Monday, February 14.
Hariri resigned late last year after heading five governments for more than 12 years.
He'd helped Lebanon rebuild after 15 years of civil war.
Well over 100,000 marched in a funeral parade, voicing opposition to Syria which has been in the country since 1970 and currently has 14,000 troops there.
Opposition leaders hold Lebanon and Syrian governments responsible for the bombing.
Led by the U.S. and France, international pressure grows for Syria to withdraw from Lebanon.
