Coral reefs provide seafood and livelihood for one billion Asians alone, many from impoverished areas.
Over 58% of the world's coral reefs are endangered because of pollution, over-fishing, disease, and climate change.
Reefs suffer from hurricanes and El Nino-triggered bleaching.
Coral reef damage from the late December Indian Ocean tsunamis is yet to be assessed.
About 30% of the world's coral reefs are healthy, down from 41% two years ago.
About two-fifths of those damaged in the 1998 El Nino bleaching have since recovered.
Taiwan is constructing artificial reefs to act as foundations to support new living coral colonies.
