Aid has begun to pour into Indonesia, hardest hit by the December 26, 2004 tsunami.
This tsunami was caused by an earthquake off northern Sumatra that registered 8.7 on the Richter scale.
Aceh Province and North Sumatra were hardest hit with more than 100,000 killed in Sumatra and 500,000 homeless in Aceh Province.
Offered aid included $2.62 million from China, $146 million and military teams from Japan, $764 million from Australia, humanitarian aid from Bangladesh and Uzbekistan, and Uzbekistan transporting supplies from Denmark and Switzerland.
Indonesia has scheduled a summit of world leaders for January 6.
