Among the world's oldest and most diverse forms of life, coral reefs provide food and shelter to fish as well as humans, protect shores from erosion, and provide economic livelihoods based on fishing and tourism.
More than 58% of the world's coral reefs are threatened by disease, pollution, over-fishing, weather and tidal conditions, coastal development, and encroachment of introduced species.
Their destruction impacts over one billion people and threatens over 15,000 species with extinction.
Protection efforts include fishing restrictions, coral reef trade limitations, artificial reefs, satellite monitoring, and possibly the introduction of more heat-tolerant co-habiting species.
