Explosions at a petrochemical plant on 13 November caused major water pollution by benzene and nitrobenzene on northeastern China’s Songhua River.
The density was almost 30 times the standard; the polluted swath was 80 kilometers long.
The water supply was turned off in Harbin, population about 4 million.
The pollution has injured no one because timely countermeasures were taken: the entry of pollutants was blocked, reservoir water was released to dilute thee pollutants, and monitoring was increased.
The plant was about 150 km from the Chinese Russian border.
The Songhua River is called the Amur River in Russia.
