Former Lebanese Prime Minister Rafik Hariri was killed in a suicide car bombing in Beirut on 14 February At least 14 others were killed and about 120 injured in the blast that hit his motorcade.
A previously unknown Islamic group has claimed responsibility.
The opposition leader blamed Syria and demanded that Syria withdraw its 14,000 troops still in Lebanon.
There is also renewed international pressure for a Syrian troop withdrawal.
Syria condemned the attack and denied involvement.
Well over 100,000 mourners attended the funeral.
Hariri and the other victims were buried on the grounds of an unfinished mosque in Beirut.
