Pfc Lynndie England, a West Virginia Army reservist involved in the Abu Ghraib prison photographs, pled guilty to two counts of conspiracy, four of mistreating prisoners, and one of indecency.
She has a history of mental problems and learning disabilities and trained as a records clerk, unaware of the Geneva Convention.
England said that she was doing as she was told, that she trusted her boyfriend, Spec.
Charles Graner, the ringleader and her baby's father, because he was a prison guard, an MP, and older.
A military jury will convene on 3 May to recommend a sentence.
