Robert Blake, a 71 year-old actor, is on trial for shooting his wife, Bonny Lee Bakley, on May 4, 2001, in his car after dining at an Italian restaurant.
He is charged with murder, two counts of solicitation of murder, and special circumstance of lying in wait.
If convicted he would face life in prison.
He pled not guilty.
The trial is occurring in the Van Nuys Superior Court of Los Angles.
Deputy District Attorney Shellie Samuels is prosecuting and M. Gerald Schwartzbach is the defense attorney.
Closing arguments for the 2-month trial began on February 26, 2005.
