On December 26, 2004, an 8.7 magnitude earthquake, the biggest in the world in 40 years, unleashed a tsunami that slammed into coastal communities from southern Asia to Africa, killing nearly 150,000 in 11 nations.
Indonesia's death toll had reached 94,200 and was expected to top 100,000 on hardest-hit Sumatra Island, and 500,000 Indonesians were left homeless.
Sumatra was the focus of a massive international aid effort with foreign militaries, led by the US, flying in assistance.
On January 6, Indonesia would host a summit of world leaders from 23 countries to discuss the aftermath of the disaster.
