Britain's Food Standards Agency ordered 474 foods recalled because they contain the dye Sudan I, used to color products like oils and shoe polish.
The EU has banned its use in foods because of an increased, albeit small, risk of cancer.
The foods were all made with worcestershire sauce which contained the chili powder.
All chili powder imported since July 2003 must be certified free of the agent.
Since worcestershire sauce takes a long time to mature, the powder probably entered Britain before the ban.
Britain ordered a thorough investigation.
The discovery has sparked an international food safety alert.
