name: Summary
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - gensim
  - networkx
  - nltk
  - spacy
  - scikit-learn  
  - absl-py
  - six>=1.14
  - rouge-score
  - pip
  - pip:
    - contractions
