name: Summary
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - gensim
  - networkx
  - nltk
  - spacy
  - scikit-learn  
  - absl-py
  - six>=1.14
  - rouge-score
  - os
  - pip
  - pytorch=1.12.1  # Add PyTorch to ensure compatibility with the transformers library
  - transformers  # This will attempt to get the latest version available on conda channels
  - sentence-transformers
  - pip:
    - contractions