name: Summary
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - gensim
  - nltk
  - spacy
  - scikit-learn  
  - pip
  - os
  - networkx
  - pip:
    - contractions
