name: Summary
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - empath
  - gensim
  - nltk
  - spacy
  - scikit-learn
  - pyyaml  
  - emoji
  - pip
  - pip:
    - contractions